#ifndef HEADERS_FUNCTIONS_ARM9_H_
#define HEADERS_FUNCTIONS_ARM9_H_
void _start(void);
void ret_02000b98(void);
void ret_02000b9c(void);
void NitroMain(void);
void ret_0200120c(void);
void* MaybeMemAlloc(undefined4 param_1);
void GF_Assert_Veneer(void);
void LoadOverlay(int overlay, bool param_2);
undefined* SetGameState(int state, struct megastruct* param_2);
void InitControllerInputs(struct controller_inputs* param_1);
void ret_02001eb4(void);
void ret_02001ecc(void);
void ret_0200372c(void);
void ret_0200396c(void);
void ret_02003984(void);
void ret_02007ca8(void);
void ret_02007cc0(void);
void ret_02008ed8(void);
void ret_0200bbc0(void);
void ret_0200bbc4(void);
void ret_0200c404(void);
void ret_0200d414(void);
void ret_0200ee10(void);
void ret_0200fa58(void);
struct megastruct* InitMegastruct(struct megastruct* param_1);
struct megastruct* GetMegastructPointer(void);
void ret_02010448(void);
void InitializeBattlePokemonFields(struct battle_combatants* param_1);
void BattleSetUnkField0x0(struct battle_combatants* param_1, int* param_2);
void BattleSetCurrentHp(struct battle_combatants* param_1, int8_t param_2);
void BattleSetStylerLevel(struct battle_combatants* param_1, int8_t param_2);
void BattleSetPartnerAssistUnlockStatus(struct battle_combatants* param_1, int param_2);
void GetPartnerGaugeCurrent(struct battle_combatants* param_1, int param_2);
void BattleSetPartnerGaugeMax(struct battle_combatants* param_1, int param_2);
void BattleSetPartnerGaugeFillRate(struct battle_combatants* param_1, int param_2);
void BattleAddPartyPokemon(struct battle_combatants* param_1, int16_t form_id, int8_t param_3);
void BattleTryAddNewEnemyForm(struct battle_combatants* param_1, unsigned int param_2,
                              unsigned int param_3);
void BattleSetArenaGraphicId(struct battle_combatants* param_1, int8_t param_2);
void BattleSetWeatherEffectId(struct battle_combatants* param_1, int8_t param_2);
void BattleSetSequenceScriptId(struct battle_combatants* param_1, int8_t param_2);
void BattleSetTutorialScriptId(struct battle_combatants* param_1, int8_t param_2);
void BattleSetStartScriptId(struct battle_combatants* param_1, int8_t param_2);
void BattleSetBgmId(struct battle_combatants* param_1, int8_t param_2);
void BattleSetViewPartyStatus(struct battle_combatants* param_1, int param_2);
void BattleSetCanFleeStatus(struct battle_combatants* param_1, int param_2);
void BattleSetBossFightStatus(struct battle_combatants* param_1, int param_2);
void BattleSetUnkField0x52(struct battle_combatants* param_1, int8_t param_2);
void BattleSetUnkField0x54(struct battle_combatants* param_1, int8_t param_2);
void BattleSetGenderAndUniform(struct battle_combatants* param_1, int16_t param_2);
int* BattleGetUnkField0x0(struct battle_combatants* param_1);
int8_t BattleGetCurrentHp(struct battle_combatants* param_1);
int8_t BattleGetStylerLevel(struct battle_combatants* param_1);
bool BattleCanPartnerUsePokeAssist(struct battle_combatants* param_1);
int BattleGetPartnerGaugeCurrent(struct battle_combatants* param_1);
int BattleGetPartnerGaugeMax(struct battle_combatants* param_1);
int BattleGetPartnerGaugeFillRate(struct battle_combatants* param_1);
int8_t BattleGetNumEnemyForms(struct battle_combatants* param_1);
int16_t BattleGetEnemyFormId(struct battle_combatants* param_1, int param_2);
int8_t BattleGetEnemyCount(struct battle_combatants* param_1);
int8_t BattleGetUnkEnemyData0x41(struct battle_combatants* param_1, int param_2);
int8_t BattleGetPartyPokemonCount(struct battle_combatants* param_1);
int16_t BattleGetPartyFormIds(struct battle_combatants* param_1, int param_2);
int8_t BattleGetPartySlotStatusesById(struct battle_combatants* param_1, int param_2);
int8_t BattleGetArenaGraphicId(struct battle_combatants* param_1);
int8_t BattleGetSequenceScriptId(struct battle_combatants* param_1);
int8_t BattleGetTutorialScriptId(struct battle_combatants* param_1);
int8_t BattleGetStartScriptId(struct battle_combatants* param_1);
int8_t BattleGetBgmId(struct battle_combatants* param_1);
bool BattleGetViewPartyStatus(struct battle_combatants* param_1);
bool BattleGetCanFleeStatus(struct battle_combatants* param_1);
bool BattleGetBossFightStatus(struct battle_combatants* param_1);
int8_t BattleGetUnkField0x52(struct battle_combatants* param_1);
int8_t BattleGetFieldAllocBits(struct battle_combatants* param_1);
int8_t BattleGetUnkField0x54(struct battle_combatants* param_1);
int16_t BattleGetGenderAndUniform(struct battle_combatants* param_1);
struct battle_exports* InitBattleExports(struct battle_exports* param_1);
void ret_02010cec(void);
void ZeroBattleExports(struct battle_exports* param_1);
void ZeroQuestBody(struct quest* param_1);
void ZeroQuestFooter(struct quest* param_1);
void InitMissionQuestFooter(struct mission_quest_data* param_1, struct script_manager* param_2,
                            undefined* param_3);
void TryUnlockQuest(struct mission_quest_data* param_1, int param_2);
bool IsQuestAvailable(struct mission_quest_data* param_1, int param_2);
void MakeQuestNameVisible(struct mission_quest_data* param_1, int param_2);
bool HasClearedQuest(struct mission_quest_data* param_1, int param_2);
void TryAcceptQuest(struct mission_quest_data* param_1, int param_2);
void TryClearQuest(struct mission_quest_data* param_1);
void TryBackOutOfQuest(struct mission_quest_data* param_1);
bool ShouldShowQuestName(struct mission_quest_data* param_1, int param_2);
void ret_020117ac(void);
void ZeroPokemonData(struct pokemon_data* param_1);
void ret_02015108(void);
void ret_02015120(void);
void MaybeInitRangerData(struct ranger_data_old* param_1);
struct pokemon_data* RetrievePokemonByFormId(struct ranger_data_old* param_1, int form_id);
struct pokemon_data* RetrievePokemonDataFromTable(struct ranger_data* param_1, int param_2);
undefined4 IsTriggerSpawnNibbleUnlocked(struct ranger_data* param_1, int param_2,
                                        enum room_id param_3);
void UnlockTriggerSpawnNibble(struct ranger_data* param_1, int param_2, enum room_id param_3);
void EnableTriggerSpawnNibble(struct ranger_data* param_1, int param_2, enum room_id param_3);
void UnlockPokemonSpawnNibble(struct ranger_data* param_1, int param_2, enum room_id param_3);
void EnablePokemonSpawnNibble(struct ranger_data* param_1, int param_2, enum room_id param_3);
undefined4 IsNpcSpawnNibbleUnlocked(struct ranger_data* param_1, int param_2, enum room_id param_3);
void UnlockNpcSpawnNibble(struct ranger_data* param_1, int param_2, enum room_id param_3);
void EnableNpcSpawnNibble(struct ranger_data* param_1, int param_2, enum room_id param_3);
void MaybeHandleStylerLevelUp(struct ranger_data* param_1, unsigned int styler_level);
void UpdatePlayTime(struct ranger_data* param_1);
void DebugPrint(char* fmt, ...);
void AssignPartnerMoods(struct ranger_data* param_1);
unsigned int GetStylerUpgradeById(struct ranger_data* param_1, int param_2);
void SetPlayerExp(struct ranger_data* param_1, uint32_t param_2);
int32_t AddPlayerExp(struct ranger_data* param_1, int32_t param_2);
void SetMaxStepsRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddMaxStepsRecord(struct ranger_data* param_1, int32_t param_2);
void SetConversationsRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddConversationsRecord(struct ranger_data* param_1, int32_t param_2);
void SetTargetsCheckedRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddTargetsCheckedRecord(struct ranger_data* param_1, int32_t param_2);
void SetGameSavesRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddGameSavesRecord(struct ranger_data* param_1, int32_t param_2);
void SetPokemonRidesRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddPokemonRidesRecord(struct ranger_data* param_1, int32_t param_2);
void SetPartnerPokemonBestnessIfGreaterByIndex(struct ranger_data* param_1, int param_2,
                                               unsigned int param_3);
int32_t IncrementPartnerPokeAssistsBySpecies(struct ranger_data* param_1, int16_t param_2,
                                             int param_3);
undefined2 MaybeGetBestPartnerRecord(struct ranger_data* param_1);
void SetCaptureLineLenRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddCaptureLineLenRecord(struct ranger_data* param_1, int32_t param_2);
void SetNumLoopsRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddNumLoopsRecord(struct ranger_data* param_1, int32_t param_2);
void SetPokemonCapturedRecord(struct ranger_data* param_1, int16_t param_2);
int16_t AddPokemonCapturedRecord(struct ranger_data* param_1, int16_t param_2);
void SetFledPokemonRecord(struct ranger_data* param_1, int16_t param_2);
int16_t AddFledPokemonRecord(struct ranger_data* param_1, int16_t pokemon_fled);
void SetPokeAssistsUsedRecord(struct ranger_data* param_1, int16_t param_2);
int16_t AddPokeAssistsUsedRecord(struct ranger_data* param_1, int16_t param_2);
bool CheckSaveFileValidity(void);
void ZeroSettingsAndVariables(struct settings_and_variables* param_1);
void ZeroEventVariables(struct settings_and_variables* param_1);
void SetEventVariable(struct settings_and_variables* param_1, int32_t param_2, int32_t param_3);
int32_t GetEventVariable(struct settings_and_variables* param_1, int32_t param_2);
void ZeroQuestVariables(struct settings_and_variables* param_1);
void SetQuestVariable(struct settings_and_variables* param_1, int32_t param_2, int32_t param_3);
int32_t GetQuestVariable(struct settings_and_variables* param_1, int32_t param_2);
void SetSettingsVariable(struct settings_and_variables* param_1, int param_2, int32_t param_3);
int32_t GetSettingsVariable(struct settings_and_variables* param_1, int param_2);
void ret_0201a40c(void);
void ret_020222c8(void);
void ret_020222cc(void);
void ret_020222d0(void);
void ret_020222d4(void);
void ret_02022710(void);
void ret_020228c0(void);
void ret_020237e0(void);
void ret_02029778(void);
void ret_0202a5f8(void);
void ret_0202d394(void);
void DebugPrintError(char* fmt, ...);
undefined4 CopyStringToRangerDebugBuffer(char** param_1);
undefined4 BattleSetBgmIdSafe(undefined4* param_1);
undefined4 BattleSetUnkField0x49Safe(undefined4* param_1);
int GetBattleResultSafe(void);
undefined4 BattleDisableFleeing(void);
undefined4 BattleSetUnkField0x54Safe(undefined4* param_1);
undefined4 BattleSetSequenceScriptIdSafe(undefined4* param_1);
undefined4 BattleSetTutorialScriptIdSafe(undefined4* param_1);
undefined4 BattleSetStartScriptIdSafe(undefined4* param_1);
undefined4 BattleSetStylerLevelSafe(undefined4* param_1);
undefined4 BattleAddPartyPokemonSafe(undefined4* param_1);
void AddEnemyFormToEncounterType1(undefined4* param_1);
undefined4 BattleSetBossFightStatusSafe(void);
int8_t GetRangerStylerRank(void);
int32_t GetRangerStylerType(void);
int8_t GetStylerLevelSafe(void);
undefined4 SysCallSetRangerCurrentHP(uint *param_1);
int8_t GetRangerMaxHpSafe(void);
int8_t GetRangerCurrentHpSafe(void);
undefined4 TryClearQuestSafe(void);
int8_t GetActiveQuestIdSafe(void);
undefined4 TryBackOutOfQuestSafe(void);
int GetChapterNumber(void);
undefined4 EnableSlotStatusBit2(struct pokemon_data* param_1);
undefined4 DisableSlotStatusBit2(struct pokemon_data* param_1);
undefined4 EnableSlotStatusBit1(struct pokemon_data* param_1);
undefined4 DisableSlotStatusBit1(struct pokemon_data* param_1);
undefined4 BitorPartnerPokemonStatus(uint32_t* param_1);
uint32_t BitandPartnerPokemonStatus(uint32_t* param_1);
int8_t GetPartnerPokemonMood(int* param_1);
void ret_02032a44(void);
void ret_0203331c(void);
void ret_02033388(void);
void ret_020333d8(void);
void ret_02033440(void);
void ret_0203365c(void);
void DisableActiveTimersAndMore(void);
void InitTimerType1(int32_t* param_1);
void InitTimerType2(int32_t* param_1);
void SetTimerTypeNone(void);
undefined4 SetTimerType1(void);
undefined4 SetTimerType2(void);
int32_t GetTimer1Duration(void);
undefined4 SetTimer1Duration(int32_t* param_1);
undefined4 TimerIsActive(void);
undefined4 IncrementPokemonRidesRecord(void);
int32_t GetGameSavesRecordSafe(void);
undefined4 SetScriptSubroutine1(struct script_data* param_1, char* param_2, undefined4 param_3,
                                undefined4 param_4);
void SetScriptSubroutine2(struct script_data* param_1, char* param_2, undefined4 param_3,
                          undefined4 param_4);
void ZeroInitScriptData(struct script_data* param_1);
struct script_manager* AllocateQuestDataPtrsAndMore(struct script_manager* param_1,
                                                    undefined4* param_2);
int TryInitSystemScript(struct script_manager* param_1, int param_2);
int TryInitAreaScript(struct script_manager* param_1, int param_2, undefined4 param_3,
                      undefined4 param_4);
int TryInitChapterScript(struct script_manager* param_1, int param_2, undefined4 param_3,
                         undefined4 param_4);
void TryInitQuestScript(struct script_manager* param_1, int param_2);
undefined4 SetScriptSubroutine1ByName(struct script_manager* param_1, char* param_2);
void SetScriptSubroutine2ByName(struct script_manager* param_1, char* param_2,
                                struct megastruct* param_3, undefined4 param_4);
void ZeroInitSystemScriptData(struct script_manager* param_1);
void ZeroInitAreaScriptData(struct script_manager* param_1);
void ZeroInitChapterScriptData(struct script_manager* param_1);
void ZeroInitQuestScriptData(struct script_manager* param_1);
void SetUnkRidingData(struct script_manager* param_1, undefined4 param_2);
undefined4 GetUnkRidingData(struct script_manager* param_1);
void ZeroInitAllScriptData(struct script_manager* param_1);
undefined4 GetPartnerIndexFromFormId(enum form_id param_1);
undefined4 GetPartnerIndexFromFormIdAgain(enum form_id param_1);
void ret_020358fc(void);
void ret_02035fe4(void);
void ret_0203e930(void);
void ret_0204078c(void);
void ret_0204129c(void);
void ret_02041920(void);
void ret_02043124(void);
void ret_02043128(void);
void ret_020439c4(void);
void ret_020439c8(void);
void ret_02044144(void);
void ret_02044148(void);
void ret_020441ac(void);
void DebugPrintInternal(char* format, va_list ap);
void DebugPrintInternalVeneer(char* format, va_list ap);
void ret_02046d3c(void);
int32_t close(int32_t fd);
int32_t socket(int32_t domain, int32_t family, int32_t protocol);
int32_t bind(int32_t sockfd, const struct sockaddr_in* addr);
int32_t connect(int32_t sockfd, const struct sockaddr_in* addr);
int32_t recv(int32_t sockfd, void* buf, size_t size, int32_t flags);
int32_t recvfrom(int32_t sockfd, void* buf, size_t size, int32_t flags, struct sockaddr_in* addr,
                 int32_t addr_len);
int32_t send(int32_t sockfd, const void* buf, size_t size, int32_t flags);
int CloseVeneer(int _fd);
void ret_02049d08(void);
void ret_0205fc98(void);
void ret_0205fcb8(void);
undefined4* Mtx_Identity22(undefined4* param_1);
undefined4* Mtx_Scale22(undefined4* param_1, undefined4 param_2, undefined4 param_3);
undefined4* Mtx_Identity33(undefined4* param_1);
void Mtx_RotZ33(undefined4* param_1, int param_2, undefined4 param_3);
undefined4* Mtx_Identity44(undefined4* param_1);
void Mtx_TransApply44(int* param_1, int* param_2, int param_3, int param_4, int param_5);
void Mtx_ScaleApply44(unsigned int* param_1, unsigned int* param_2, int param_3, int param_4,
                      int param_5);
undefined4* Mtx_RotZ44(undefined4* param_1, int param_2, undefined4 param_3);
void FixedPoint4x4MatrixMultiply(int* param_1, int* param_2, unsigned int* param_3,
                                 undefined4 param_4);
void Mtx_OrthoW(int param_1, int param_2, int param_3, int param_4, int param_5, int param_6,
                unsigned int param_7, int* param_8);
void ret_0206129c(void);
void GX_Init(void);
void GX_SetVCountEqVal(unsigned int param_1);
uint16_t GX_HBlankIntr(int param_1, uint16_t param_2);
uint16_t GX_VBlankIntr(int param_1, uint16_t param_2);
void GX_DispOff(void);
void GX_DispOn(void);
void GX_SetGraphicsMode(uint16_t param_1,uint param_2,int param_3);
void GX_InitGxState(void);
void G3_LoadMtx44(void);
void G3_LoadMtx43(void);
void G3i_OrthoW_(int param_1,int param_2,int param_3,int param_4,int param_5,int param_6,uint param_7,int param_8,int *param_9);
void G3_LoadTexMtxTexCoord(undefined4 *param_1);
undefined4 * GX_SendFifo64B(undefined4 *param_1,undefined4 *param_2);
void OS_WaitIrq(int param_1, unsigned int param_2);
void ret_020647a0(void);
void OS_InitIrqTable(void);
void OS_SetIrqFunction(uint32_t intr_bit, os_irq_function function);
undefined4 OS_GetIrqFunction(uint param_1);
void OSi_EnterDmaCallback(int param_1,undefined4 param_2,undefined4 param_3);
void OSi_EnterTimerCallback(int param_1,undefined4 param_2,undefined4 param_3);
uint32_t OS_SetIrqMask(uint32_t mask);
uint32_t OS_EnableIrqMask(uint32_t mask);
uint32_t OS_DisableIrqMask(uint32_t mask);
uint32_t OS_ResetRequestIrqMask(uint32_t mask);
void OS_SetIrqStackChecker(void);
void OS_InitLock(void);
void OSi_DoLockByWord(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int32_t OS_LockByWord(uint16_t lock_id, struct os_lock_word* lockp, lock_ctrl_funcp ctrl_funcp);
undefined4 OSi_DoUnlockByWord(uint param_1,undefined4 *param_2,void* *param_3,int param_4);
int32_t OS_UnlockByWord(uint16_t lock_id, struct os_lock_word* lockp, lock_ctrl_funcp ctrl_funcp);
int OSi_DoTryLockByWord(undefined4 param_1,int param_2,void* *param_3,int param_4);
undefined4 OS_LockCartridge(undefined4 param_1);
int32_t OS_UnlockCartridge(uint16_t lock_id);
int32_t OS_UnlockCartridgeVeneer(uint16_t lock_id);
undefined4 OS_TryLockCartridge(undefined4 param_1);
void OSi_LockCardID(void);
void OSi_UnlockCardID(void);
void OS_LockCard(undefined4 param_1);
void OS_UnlockCard(undefined4 param_1);
void OSi_AllocateCardBus(void);
void OSi_FreeCardBus(void);
undefined2 OS_ReadOwnerOfLockWord(int param_1);
int32_t OS_GetLockID(void);
void OS_ReleaseLockID(int param_1);
void MaybeCopyFileName(char* param_1, char* param_2, undefined4 param_3, undefined4 param_4);
void OSi_GetUnusedThreadId(void);
void OSi_InsertLinkToQueue(struct os_thread_queue* queue, struct thread* thread);
int OSi_RemoveLinkFromQueue(int *param_1);
int OSi_RemoveSpecifiedLinkFromQueue(int *param_1,int param_2);
int OSi_RemoveMutexLinkFromQueue(int *param_1);
void OSi_InsertThreadToList(struct thread* thread);
void OSi_RemoveThreadFromList(int param_1);
void OS_RescheduleThread(void);
void OS_InitThread(void);
undefined4 OS_IsThreadAvailable(void);
void OS_CreateThread(thread *param_1,undefined4 param_2,uint32_t param_3,void *param_4,int param_5,int param_6);
void OS_ExitThread(void);
void OSi_ExitThread_ArgSpecified(uint *param_1,uint param_2,undefined4 param_3,undefined4 param_4);
void OSi_ExitThread(void);
void OSi_ExitThread_Destroy(void);
void OS_DestroyThread(int param_1);
void OSi_CancelThreadAlarmForSleep(int param_1);
void OS_JoinThread(thread *param_1);
bool OS_IsThreadTerminated(int param_1);
void OS_SleepThread(struct os_thread_queue* queue);
void OS_WakeupThread(int *param_1);
void OS_WakeupThreadDirect(struct thread* thread);
void OS_SelectThread(undefined4 param_1,int param_2);
void OS_RescheduleThread(void);
undefined4 OS_SetThreadPriority(undefined *param_1,int param_2);
undefined4 OS_GetThreadPriority(int param_1);
void OS_Sleep(uint param_1);
void OSi_SleepAlarmCallback(int *param_1);
os_switch_thread_callback OS_SetSwitchThreadCallback(os_switch_thread_callback callback);
void OSi_IdleThreadProc(void* arg);
int OS_DisableScheduler(void);
int OS_EnableScheduler(void);
void OS_SetThreadDestructor(struct thread* thread, int32_t value);
void OS_InitContext(undefined4 *param_1,int param_2,int param_3);
bool OS_SaveContext(struct os_context* context);
void OS_LoadContext(struct os_context* context);
undefined4 OS_IsRunOnEmulator(void);
void OS_GetConsoleType(void);
void OS_InitMutex(struct os_mutex* mutex);
bool OS_LockMutex(undefined4 *param_1,int param_2);
void OS_UnlockMutex(int param_1);
void OSi_UnlockAllMutex(int param_1);
undefined4 OS_TryLockMutex(int param_1);
void OSi_EnqueueTail(int param_1,int param_2);
void OSi_DequeueItem(int param_1,int param_2);
undefined4 DC_InvalidateAll(void);
void DC_Store_All(void);
void DC_FlushAll(void);
void DC_InvalidateRange(void* start_addr, uint32_t n_bytes);
void DC_StoreRange(unsigned int param_1, int param_2);
void DC_FlushRange(void* data, uint32_t size);
undefined4 DC_WaitWriteBufferEmpty(void);
undefined4 IC_InvalidateAll(void);
void IC_InvalidateRange(unsigned int param_1, int param_2);
void OSi_WaitVCount0(void);
void OS_Init(void);
void OS_InitArena(void);
void OS_InitArenaEx(void);
void* OS_GetArenaHi(int param_1);
void* OS_GetArenaLo(int param_1);
void* OS_GetInitArenaHi(int param_1);
void* OS_GetInitArenaLo(enum os_arena_id id);
void OS_SetArenaHi(enum os_arena_id id, void* new_hi);
void OS_SetArenaLo(enum os_arena_id id, void* new_lo);
void* OS_AllocFromArenaLo(int param_1, int param_2, int param_3);
unsigned int OS_GetDtcmAddress(void);
unsigned int OS_EnableProtectionUnit(void);
unsigned int OS_DisableProtectionUnit(void);
void OS_SetDPermissionsForProtectionRegion(unsigned int param_1, unsigned int param_2);
void OS_SetProtectionRegion1(uint32_t param);
void OS_SetProtectionRegion2(uint32_t param);
void OS_InitException(void);
void OSi_ExceptionHandler(void);
undefined4 OSi_GetAndDisplayContext(undefined4 param_1);
int OSi_SetExContext(undefined4 param_1);
void OSi_DisplayExContext(void);
void OSi_DisplayExContext_Helper(void);
void OSi_SetTimerReserved(uint param_1);
void OSi_UnsetTimerReserved(uint param_1);
void OS_InitTick(void);
bool OS_IsTickAvailable(void);
void OSi_CountUpTick(void);
int64_t OS_GetTick(void);
undefined2 OS_GetTickLo(void);
void OSi_SetTimer(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void OS_InitAlarm(void);
void OS_EndAlarm(void);
undefined2 OS_IsAlarmAvailable(void);
void OS_CreateAlarm(undefined4 *param_1);
void OSi_InsertAlarm(int param_1,undefined4 param_2,undefined4 param_3);
void OS_SetAlarm(int *param_1,undefined4 param_2,undefined4 param_3,int param_4,int param_5);
void OS_CancelAlarm(int *param_1);
undefined4 OSi_AlarmHandler(undefined4 param_1);
void OSi_ArrangeTimer(void);
void OS_InitVAlarm(void);
void OS_EndVAlarm(void);
void OSi_InsertVAlarm(int param_1);
void OSi_AppendVAlarm(int param_1);
void OSi_DetachVAlarm(int param_1);
void OS_CreateVAlarm(undefined4* param_1);
void OS_SetVAlarm(int* param_1, int param_2, undefined2 param_3, int param_4, int param_5);
void OS_SetPeriodicVAlarm(int* param_1, int param_2, undefined2 param_3, int param_4, int param_5);
void OSi_SetNextVAlarm(int param_1);
void OS_CancelVAlarm(int* param_1);
void OS_CancelAllVAlarms(void);
void OSi_VAlarmHandler(void);
undefined4 OSi_CompareVCount(int param_1, int param_2, int param_3);
undefined4 OSi_GetVFrame(int param_1);
long long OS_EnableInterrupts(void);
int32_t OS_DisableInterrupts(void);
int32_t OS_RestoreInterrupts(int32_t new_value);
long long OS_EnableInterrupts_IrqAndFiq(void);
undefined4 OS_RestoreInterrupts_IrqAndFiq(void);
undefined4 OS_GetCpsrIrq(void);
undefined4 OS_GetProcMode(void);
void OS_SpinWait(unsigned int param_1);
void OS_WaitVBlankIntr(void);
void OS_InitReset(void);
void OSi_CommonCallback(undefined4 param_1, unsigned int param_2);
void OSi_SendToPxi(uint16_t param_1);
void OS_ResetSystem(undefined4 param_1);
void OS_GetMacAddress(uint8_t* macAddress);
void OS_GetOwnerInfo(struct user_settings* settings);
uint32_t Math_CountLeadingZeros(uint32_t x);
void OSi_InitVramExclusive(void);
bool OSi_TryLockVram(uint16_t param_1, uint16_t param_2);
void OSi_UnlockVram(uint16_t param_1, uint16_t param_2);
void OS_GetLowEntropyData(uint *param_1);
void OS_Panic(void);
void OS_Halt(void);
void MI_SetWramBank(enum mi_wram cnt);
void MI_DmaFill32(int param_1, undefined4 param_2, undefined4 param_3, unsigned int param_4);
void MI_DmaSend32(int param_1, undefined4 param_2, undefined4 param_3, unsigned int param_4);
void MI_DmaFill16(int param_1, undefined4 param_2, undefined4 param_3, unsigned int param_4);
void MI_DmaCopy16(uint32_t dma_no, void* src, void* dest, uint32_t size);
void MI_StopDma(uint32_t dma_no);
void MIi_CheckAnotherAutoDma(int param_1, unsigned int param_2);
void MIi_CheckDma0SourceAddress(uint32_t dma_no, uint32_t src, uint32_t size, uint32_t dir);
void MIi_CpuClear16(uint16_t val, void* ptr, int32_t len);
void MIi_CpuCopy16(void* src, void* dest, int32_t len);
void MIi_CpuClear32(uint32_t val, void* ptr, int32_t len);
void MIi_CpuCopy32(void* src, void* dest, int32_t len);
void MIi_CpuClearFast(uint32_t val, void* ptr, int32_t len);
void MIi_CpuCopyFast(void* src, void* dest, int32_t len);
int64_t MI_Copy36B(undefined4* param_1, undefined4* param_2);
int64_t MI_Copy48B(undefined4* param_1, undefined4* param_2);
void MI_CpuFill8(void* ptr, char val, uint32_t len);
void MI_CpuCopy8(void* src, void* dest, uint32_t n);
undefined4 MI_SwapWord(undefined4 param_1, undefined4* param_2);
void MIi_CardDmaCopy32(int param_1, undefined4 param_2, undefined4 param_3, int param_4);
void MI_Init(void);
void SND_SetupAlarm(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5);
void PushCommand_impl(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5);
void SND_Init(void);
bool SNDi_LockMutex(undefined4 param_1);
void SNDi_UnlockMutex(void);
void SND_CommandInit(void);
int * SND_RecvCommandReply(uint param_1);
void SND_AllocCommand(uint param_1);
void SND_PushCommand(undefined4 *param_1);
undefined4 SND_FlushCommand(uint param_1);
void SND_WaitForCommandProc(undefined4 param_1);
undefined4 SND_GetCurrentCommandTag(void);
bool SND_IsFinishedCommandTag(uint param_1);
int SND_CountFreeCommand(void);
int SND_CountReservedCommand(void);
int SND_CountWaitingCommand(void);
void PxiFifoCallback(undefined4 param_1,undefined4 param_2);
void InitPXI(void);
void RequestCommandProc(void);
int * AllocCommand(void);
bool IsCommandAvailable(void);
void SND_AlarmInit(void);
char SNDi_SetAlarmHandler(int param_1,undefined4 param_2,undefined4 param_3);
void SNDi_CallAlarmHandler(uint param_1);
uint16_t Snd_CalcChannelVolume(int32_t value);
void Pxi_Init(void);
void Pxi_InitFifo(void);
void Pxi_SetFifoRecvCallback(int32_t fifo_tag, pxi_fifo_callback callback);
void Pxi_IsCallbackReady(int32_t fifo_tag, enum pxi_proc proc);
int32_t Pxi_SendWordByFifo(int32_t fifo_tag, uint32_t data, bool err);
void Pxii_HandlerRecvFifoNotEmpty(void);
void TP_Init(void);
void TP_GetUserInfo(undefined* param_1);
void TP_SetCalibrateParam(int16_t* param_1);
void TP_RequestSamplingAsync(void);
undefined4 TP_WaitRawResult(undefined2 *param_1);
void TP_RequestAutoSamplingStartAsync(uint param_1,uint param_2,undefined4 param_3,uint param_4);
void TP_RequestSetStabilityAsync(void);
undefined2 TP_GetLatestIndexInAuto(void);
undefined2* TP_CalcCalibrateParam(undefined2* param_1, undefined2* param_2, unsigned int param_3,
                                  unsigned int param_4, uint16_t param_5, uint16_t param_6,
                                  uint16_t param_7, uint16_t param_8, uint16_t param_9);
void TP_GetCalibratedPoint(uint16_t* param_1, uint16_t* param_2);
void TP_WaitBusy(uint16_t param_1);
uint16_t TP_CheckBusy(uint16_t param_1);
undefined4 PMi_Lock(void);
void PMi_WaitBusy(void);
void PMi_DummyCallback(undefined4 param_1, undefined4* param_2);
void PMi_CallCallbackAndUnlock(void);
void PM_Init(void);
void PMi_CommonCallback(void);
undefined4 PMi_SendSleepStart(unsigned int param_1, unsigned int param_2);
undefined4 PM_SendUtilityCommandAsync(unsigned int param_1, undefined4 param_2, undefined4 param_3);
undefined4 PMi_ReadRegisterAsync(unsigned int param_1, undefined4 param_2, undefined4 param_3,
                                 undefined4 param_4);
int PMi_ReadRegister(uint16_t param_1, uint16_t* param_2);
void PMi_SetLedAsync(int param_1, undefined4 param_2, undefined4 param_3);
int PMi_SetLed(undefined4 param_1, undefined4 param_2, undefined4 param_3, int param_4);
undefined4 PM_SetBackLightAsync(int param_1, int param_2, undefined4 param_3, undefined4 param_4);
int PM_SetBackLight(undefined4 param_1, undefined4 param_2);
void PM_ForceToPowerOffAsync(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                             undefined4 param_4);
uint32_t PM_ForceToPowerOff(void);
void PM_GetBackLight(unsigned int* param_1, unsigned int* param_2, undefined4 param_3,
                     unsigned int param_4);
void PMi_SendPxiData(undefined4 param_1);
void PM_GoSleepMode(unsigned int param_1, uint16_t param_2, uint16_t param_3, undefined4 param_4);
undefined4 PMi_SetLcdPower(int param_1, int param_2, int param_3, int param_4);
void PM_SetLcdPower(int param_1);
bool PM_GetLcdPower(void);
undefined4 PMi_SendLedPatternCommandAsync(unsigned int param_1, undefined4 param_2,
                                          undefined4 param_3);
int PMi_SendLedPatternCommand(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                              int param_4);
undefined4 PM_GetLedPatternAsync(undefined4 param_1, undefined4 param_2, undefined4 param_3);
void PMi_PrependList(int* param_1, int param_2);
void PMi_AppendList(int* param_1, int param_2);
void PMi_DeleteList(int* param_1, int param_2, int param_3, int param_4);
void PMi_ExecuteList(undefined4* param_1);
void PM_PrependPreSleepCallback(undefined4 param_1);
void PM_AppendPostSleepCallback(undefined4 param_1);
void PM_DeletePreSleepCallback(undefined4 param_1);
void PM_DeletePostSleepCallback(undefined4 param_1);
void Rtc_Init(void);
undefined4 Rtc_GetDateAsync(undefined4 param_1, undefined4 param_2, undefined4 param_3);
undefined4 Rtc_GetDate(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                       undefined4 param_4);
undefined4 Rtc_GetTimeAsync(undefined4 param_1, undefined4 param_2, undefined4 param_3);
undefined4 Rtc_GetTime(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                       undefined4 param_4);
undefined4 Rtc_GetDateTimeAsync(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                                undefined4 param_4);
undefined4 Rtc_GetDateTime(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                           undefined4 param_4);
void RtcCommonCallback(undefined4 param_1, unsigned int param_2, int param_3, undefined4 param_4);
int RtcBcd2Hex(unsigned int param_1);
void RtcGetResultCallback(undefined4 param_1);
void RtcWaitBusy(void);
void Rtci_ReadRawDateTimeAsync(void);
void Rtci_ReadRawDateAsync(void);
void Rtci_ReadRawTimeAsync(void);
void Rtci_WriteRawStatus2Async(void);
bool RtcSendPxiCommand(unsigned int param_1, undefined4 param_2, undefined4 param_3,
                       undefined4 param_4);
int Rtc_ConvertDateToDay(unsigned int* param_1);
int Rtci_ConvertTimeToSecond(int* param_1);
int Rtc_ConvertDateTimeToSecond(undefined4 param_1, undefined4 param_2);
int64_t Rtc_GetDayOfWeek(int* param_1);
void Cardi_SetTask(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Cardi_LockResource(int param_1, int param_2);
void Cardi_UnlockResource(int param_1, int param_2);
void Cardi_InitCommon(void);
undefined4 Card_IsEnabled(void);
void Card_CheckEnabled(void);
void Card_Enable(bool enable);
bool Cardi_WaitAsync(void);
bool Cardi_TryWaitAsync(void);
undefined4 Card_IsAvailable(void);
void Card_LockRom(undefined4 param_1);
void Card_UnlockRom(undefined4 param_1);
void Card_LockBackup(undefined4 param_1);
void Cardi_RequestStreamCommandCore(int* param_1);
bool Cardi_RequestStreamCommand(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                                undefined4 param_4, undefined4 param_5, int param_6,
                                undefined4 param_7, undefined4 param_8, undefined4 param_9);
undefined4 Card_GetCurrentBackupType(void);
undefined4 Card_GetBackupTotalSize(void);
undefined4 Card_GetBackupSectorSize(void);
undefined4 Card_GetBackupPageSize(void);
bool Card_IdentifyBackup(int param_1);
void Card_WaitBackupAsync(void);
void Card_TryWaitBackupAsync(void);
bool Cardi_ReadFromCache(void* p);
void Cardi_SetRomOp(uint32_t cmd1, uint32_t cmd2);
void Cardi_SetCardDma(void);
void Cardi_OnReadCard(void);
bool Cardi_TryReadCardDma(int param_1);
void Cardi_ReadCard(void* p);
undefined4 Cardi_ReadRomIdCore(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                               undefined4 param_4);
void Cardi_ReadRomSyncCore(void);
void Cardi_ReadRom(unsigned int param_1, int param_2, undefined4 param_3, undefined4 param_4,
                   undefined4 param_5, undefined4 param_6, int param_7);
void Card_Init(void);
void Card_WaitRomAsync(void);
undefined* Cardi_GetRomAccessor(void);
void Cardi_OnFifoRecv(enum pxi_fifo_tag tag, uint32_t data, bool err);
void Cardi_TaskThread(void);
bool Cardi_Request(undefined4* param_1, int param_2, int param_3);
void Card_InitPulledOutCallback(void);
void Cardi_PulledOutCallback(undefined4 param_1, unsigned int param_2);
undefined4 Card_IsPulledOut(void);
void Card_TerminateForPulledOut(void);
void Cardi_CheckPulledOutCore(int param_1);
void Cardi_SendtoPxi(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                     undefined4 param_4);
void ret_0207484c(void);
void Ctrdgi_InitCommon(void);
undefined4 CTRDG_IsOptionCartridge(void);
int8_t Ctrdgi_GetModuleInfoAddr(void);
undefined4 Ctrdg_IsNumberID(void);
undefined4 Ctrdg_IsAgbCartridge(void);
undefined4 Ctrdg_IsOptionCartridge(void);
undefined2 Ctrdgi_IsAgbCartridgeAtInit(void);
undefined4 Ctrdg_IsExisting(void);
void Ctrdgi_ChangeLatestAccessCycle(void* r);
void Ctrdgi_RestoreAccessCycle(void* r);
void Ctrdgi_LockByProcessor(uint16_t lock_id, void* info);
void Ctrdgi_UnlockByProcessor(uint16_t lock_id, void* info);
void Ctrdgi_SendtoPxi(uint32_t data);
bool CTRDGi_AccessCommon(undefined4 *param_1,undefined4 param_2,undefined4 *param_3,uint param_4);
undefined4 CTRDG_IsEnabled(void);
void CTRDG_Enable(int param_1);
void CTRDG_CheckEnabled(void);
void Ctrdg_Init(void);
// If declaring these builtins causes issues, you can disable them
#ifndef PRSOA_NO_BUILTIN
void CTRDGi_InitModuleInfo(void);
void CTRDGi_CallbackForInitModuleInfo(undefined4 param_1,uint param_2);
void CTRDGi_PulledOutCallback(undefined4 param_1,uint param_2);
void CTRDG_TerminateForPulledOut(void);
void CTRDGi_CallbackForSetPhi(void);
void CTRDGi_InitTaskThread(thread *param_1);
void CTRDGi_InitTaskInfo(undefined4 param_1);
void CTRDGi_IsTaskBusy(int param_1);
int32_t abs(int32_t x);
void ret_020794d4(void);
int32_t mbtowc(wchar_t* pwc, const char* s, size_t n);
bool TryAssignByte(uint8_t* ptr, uint8_t val);
bool TryAssignByteWrapper(uint8_t* ptr, uint8_t val);
size_t wcstombs(char* dest, const wchar_t* src, size_t n);
void* memcpy(void* dest, const void* src, size_t n);
void* memmove(void* dest, const void* src, size_t n);
int __vsprintf_internal_slice(slice_append_fn_t append, struct slice* str, const char* format,
                              va_list ap);
bool TryAppendToSlice(struct slice* slice, const void* data, size_t data_len);
int __vsprintf_internal(char* str, size_t maxlen, const char* format, va_list ap);
int vsprintf(char* str, const char* format, va_list ap);
size_t strlen(const char* s);
char* strcpy(char* dest, const char* src);
char* strncpy(char* dest, const char* src, size_t n);
char* strcat(char* dest, const char* src);
int32_t strcmp(const char* s1, const char* s2);
int32_t strncmp(const char* s1, const char* s2, size_t n);
char* strchr(const char* string, int32_t c);
char* strstr(const char* haystack, const char* needle);
void ret_0207f910(void);
void ret_0207f9c0(void);
double _dadd(double a, double b);
unsigned long long _ll_ufrom_d(double d);
double _dmul(double a, double b);
double _drsub(double b, double a);
double _dsub(double a, double b);
float _fadd(float a, float b);
bool _dls(double a, double b);
bool _deq(double a, double b);
bool _fls(float a, float b);
float _frdiv(float divisor, float dividend);
float _fdiv(float dividend, float divisor);
int32_t _ffix(float f);
float _fflt(int32_t i);
float _fmul(float a, float b);
float _fsub(float a, float b);
long long _ll_mod(long long dividend, long long divisor);
long long _ll_sdiv(long long dividend, long long divisor);
unsigned long long _ll_udiv(unsigned long long dividend, unsigned long long divisor);
unsigned long long _ull_mod(unsigned long long dividend, unsigned long long divisor);
long long _ll_mul(long long a, long long b);
unsigned long long _s32_div_f(int dividend, int divisor);
void _u32_div_f(uint32_t param_1, uint32_t param_2);
void _u32_div_not_0_f(uint32_t param_1, uint32_t param_2);
void ret_02081c00(void);
void ret_02082e20(void);
void ret_02083544(void);
#endif

#endif
