#ifndef HEADERS_FUNCTIONS_ARM9_H_
#define HEADERS_FUNCTIONS_ARM9_H_

#include "arm9/itcm.h"
void _start(void);
undefined4 MIi_UncompressBackward(int param_1);
void ret_02000b98(void);
void ret_02000b9c(void);
void NitroMain(void);
void ret_0200120c(void);
void* MaybeMemAlloc(undefined4 param_1);
void GF_Assert_Veneer(void);
void LoadOverlay(int overlay, bool param_2);
undefined* SetGameState(int state, struct megastruct* param_2);
void InitControllerInputs(struct controller_inputs* param_1);
struct touch_screen_wrapper* InitTouchScreenWrapper(struct touch_screen_wrapper* param_1);
struct touch_screen* InitTouchScreen(struct touch_screen* param_1);
void ret_02001eb4(void);
void ret_02001ecc(void);
struct touch_screen_wrapper* InitTouchScreenWrapperOuter(struct touch_screen_wrapper* param_1);
struct file_wrapper* InitFileWrapper(struct file_wrapper* param_1, char* param_2, int param_3,
                                     undefined4 param_4, int param_5, int param_6);
bool ConvertFilePathToId(char* param_1);
undefined4 GetMsgLangSuffix(void);
struct file_wrapper* InitFileWrapperWithLangSuffix(struct file_wrapper* param_1, undefined4 param_2,
                                                   int param_3);
void ret_0200372c(void);
void ret_0200396c(void);
void ret_02003984(void);
void ret_02007ca8(void);
void ret_02007cc0(void);
void ret_02008ed8(void);
struct textbox_data* InitTextboxDataOuter(struct textbox_data* param_1);
void WipeTextboxData(struct textbox_data* param_1);
void ZeroInitTextboxData(struct textbox_data* param_1);
bool IsTextboxPrinting(struct textbox_data* param_1);
void CloseTextbox(struct textbox_data* param_1, int param_2, int param_3);
undefined4 IsPlayerPressingTextbox(struct textbox_data* param_1);
undefined4 IsPlayerHoldingButtonsTextbox(struct textbox_data* param_1);
void SetCustomTextSpeed(struct textbox_data* param_1, int param_2);
void SetDefaultTextSpeed(struct textbox_data* param_1);
void EnableAutoAdvanceTextWithDelay(struct textbox_data* param_1, int param_2);
void DisableAutoAdvanceText(struct textbox_data* param_1);
void EnableAutoCloseTextWithDelay(struct textbox_data* param_1, int param_2);
void DisableAutoCloseText(struct textbox_data* param_1);
void PrintTextboxById(struct textbox_data* param_1, undefined4 script_kind, undefined4 msg_id,
                      undefined4 param_4, undefined4 param_5, undefined4 param_6);
void FillSystemMsgWrapperAndId(struct textbox_data* param_1, int32_t param_2);
void ClearSystemMsgWrapperAndId(struct textbox_data* param_1);
void PrintTextboxBySystemMessageId(struct textbox_data* param_1, uint32_t param_2,
                                   undefined4 param_3, undefined4 param_4, undefined4 param_5);
void FillAreaMsgWrapperAndId(struct textbox_data* param_1, int32_t param_2);
void ClearAreaMsgWrapperAndId(struct textbox_data* param_1);
void PrintTextboxByAreaMessageId(struct textbox_data* param_1, uint32_t param_2, undefined4 param_3,
                                 undefined4 param_4, undefined4 param_5);
void FillChapterMsgWrapperAndId(struct textbox_data* param_1, int32_t param_2);
void ClearChapterMsgWrapperAndId(struct textbox_data* param_1);
void PrintTextboxByChapterMessageId(struct textbox_data* param_1, uint32_t param_2,
                                    undefined4 param_3, undefined4 param_4, undefined4 param_5);
void FillQuestMsgWrapperAndId(struct textbox_data* param_1, int32_t param_2);
void ClearQuestMsgWrapperAndId(struct textbox_data* param_1);
void PrintTextboxByQuestMessageId(struct textbox_data* param_1, uint32_t param_2,
                                  undefined4 param_3, undefined4 param_4, undefined4 param_5);
void FillBattleMsgWrapperAndId(struct textbox_data* param_1, int32_t param_2);
void ClearBattleMsgWrapperAndId(struct textbox_data* param_1);
void PrintTextboxByBattleMessageId(struct textbox_data* param_1, uint32_t param_2,
                                   undefined4 param_3, undefined4 param_4, undefined4 param_5);
undefined4 TryCloseTextbox(struct textbox_data* param_1, undefined4 param_2);
int GetYesNoMenuResult(struct textbox_data* param_1);
void ret_0200bbc0(void);
void ret_0200bbc4(void);
struct textbox_subdata* ZeroInitTextboxSubData(struct textbox_subdata* param_1);
void ret_0200c404(void);
struct font_file_data* InitFontFileData(struct font_file_data* param_1);
void ret_0200d414(void);
void InitScreenFadeStructById(struct screen_fade* param_1, undefined4* param_2);
unsigned int ScreenClampValueToRange(struct screen_fade* param_1, unsigned int param_2,
                                     unsigned int param_3, unsigned int param_4);
void ScreenInitStripesForIrisTransition(struct screen_fade* param_1, int param_2, int param_3);
void ScreenApplyIrisTransitionRadius(struct screen_fade* param_1, int param_2, int param_3);
int MaybeGetIrisCurrentWidth(struct screen_fade* param_1);
void ret_0200ee10(void);
void ret_0200fa58(void);
struct megastruct* InitMegastruct(struct megastruct* param_1);
struct megastruct* GetMegastructPointer(void);
void SetTextboxWindowAndSpeedSettings(struct megastruct* param_1);
void SetUnkAudioSettingVariables(struct megastruct* param_1);
bool GetUnkAudioSettingVariables(struct megastruct* param_1);
void InitUnkAudioSettingVariables(struct megastruct* param_1);
void ret_02010448(void);
struct battle_combatants* InitBattleCombatantsOuter(struct battle_combatants* param_1);
void InitializeBattlePokemonFields(struct battle_combatants* param_1);
void BattleSetUnkField0x0(struct battle_combatants* param_1, int* param_2);
void BattleSetCurrentHp(struct battle_combatants* param_1, int8_t param_2);
void BattleSetStylerLevel(struct battle_combatants* param_1, int8_t param_2);
void BattleSetPartnerAssistUnlockStatus(struct battle_combatants* param_1, int param_2);
void GetPartnerGaugeCurrent(struct battle_combatants* param_1, int param_2);
void BattleSetPartnerGaugeMax(struct battle_combatants* param_1, int param_2);
void BattleSetPartnerGaugeFillRate(struct battle_combatants* param_1, int param_2);
void BattleAddPartyPokemon(struct battle_combatants* param_1, int16_t form_id, int8_t param_3);
void BattleTryAddNewEnemyForm(struct battle_combatants* param_1, unsigned int param_2,
                              unsigned int param_3);
void BattleSetArenaGraphicId(struct battle_combatants* param_1, int8_t param_2);
void BattleSetWeatherEffectId(struct battle_combatants* param_1, int8_t param_2);
void BattleSetSequenceScriptId(struct battle_combatants* param_1, int8_t param_2);
void BattleSetTutorialScriptId(struct battle_combatants* param_1, int8_t param_2);
void BattleSetStartScriptId(struct battle_combatants* param_1, int8_t param_2);
void BattleSetBgmId(struct battle_combatants* param_1, int8_t param_2);
void BattleSetViewPartyStatus(struct battle_combatants* param_1, int param_2);
void BattleSetCanFleeStatus(struct battle_combatants* param_1, int param_2);
void BattleSetBossFightStatus(struct battle_combatants* param_1, int param_2);
void BattleSetUnkField0x52(struct battle_combatants* param_1, int8_t param_2);
void BattleSetUnkField0x54(struct battle_combatants* param_1, int8_t param_2);
void BattleSetGenderAndUniform(struct battle_combatants* param_1, int16_t param_2);
int* BattleGetUnkField0x0(struct battle_combatants* param_1);
int8_t BattleGetCurrentHp(struct battle_combatants* param_1);
int8_t BattleGetStylerLevel(struct battle_combatants* param_1);
bool BattleCanPartnerUsePokeAssist(struct battle_combatants* param_1);
int BattleGetPartnerGaugeCurrent(struct battle_combatants* param_1);
int BattleGetPartnerGaugeMax(struct battle_combatants* param_1);
int BattleGetPartnerGaugeFillRate(struct battle_combatants* param_1);
int8_t BattleGetNumEnemyForms(struct battle_combatants* param_1);
int16_t BattleGetEnemyFormId(struct battle_combatants* param_1, int param_2);
int8_t BattleGetEnemyCount(struct battle_combatants* param_1);
int8_t BattleGetUnkEnemyData0x41(struct battle_combatants* param_1, int param_2);
int8_t BattleGetPartyPokemonCount(struct battle_combatants* param_1);
int16_t BattleGetPartyFormIds(struct battle_combatants* param_1, int param_2);
int8_t BattleGetPartySlotStatusesById(struct battle_combatants* param_1, int param_2);
int8_t BattleGetArenaGraphicId(struct battle_combatants* param_1);
int8_t BattleGetWeatherEffectId(struct battle_combatants* param_1);
int8_t BattleGetSequenceScriptId(struct battle_combatants* param_1);
int8_t BattleGetTutorialScriptId(struct battle_combatants* param_1);
int8_t BattleGetStartScriptId(struct battle_combatants* param_1);
int8_t BattleGetBgmId(struct battle_combatants* param_1);
bool BattleGetViewPartyStatus(struct battle_combatants* param_1);
bool BattleGetCanFleeStatus(struct battle_combatants* param_1);
bool BattleGetBossFightStatus(struct battle_combatants* param_1);
int8_t BattleGetUnkField0x52(struct battle_combatants* param_1);
int8_t BattleGetFieldAllocBits(struct battle_combatants* param_1);
int8_t BattleGetUnkField0x54(struct battle_combatants* param_1);
int16_t BattleGetGenderAndUniform(struct battle_combatants* param_1);
struct battle_exports* InitBattleExports(struct battle_exports* param_1);
void ret_02010cec(void);
void ZeroBattleExports(struct battle_exports* param_1);
void InitRangerNetMissionCompletionBits(int16_t* param_1);
void SetRangerNetMissionCompletionBit(void* param_1, unsigned int param_2);
unsigned int GetRangerNetMissionCompletionBit(undefined4 param_1, unsigned int param_2);
void ZeroQuestBody(struct mission_quest_data* param_1);
void ZeroQuestFooter(struct mission_quest_data* param_1);
void InitMissionQuestFooter(struct mission_quest_data* param_1, struct script_manager* param_2,
                            undefined* param_3);
void TryUnlockQuest(struct mission_quest_data* param_1, int param_2);
bool IsQuestAvailable(struct mission_quest_data* param_1, int param_2);
void MakeQuestNameVisible(struct mission_quest_data* param_1, int param_2);
bool HasClearedQuest(struct mission_quest_data* param_1, int param_2);
void TryAcceptQuest(struct mission_quest_data* param_1, int param_2);
void TryClearQuest(struct mission_quest_data* param_1);
void TryBackOutOfQuest(struct mission_quest_data* param_1);
bool ShouldShowQuestName(struct mission_quest_data* param_1, int param_2);
void ret_020117ac(void);
void ZeroPokemonData(struct pokemon_data* param_1);
void ret_02015108(void);
void ret_02015120(void);
void MaybeInitRangerData(struct ranger_data_old* param_1);
struct pokemon_data* RetrievePokemonByFormId(struct ranger_data_old* param_1, int form_id);
struct pokemon_data* RetrievePokemonDataFromTable(struct ranger_data* param_1, int param_2);
int8_t GetPartySize(struct ranger_data_old* param_1, uint32_t param_2);
undefined4 IsTriggerSpawnNibbleUnlocked(struct ranger_data* param_1, int param_2,
                                        enum room_id param_3);
void UnlockTriggerSpawnNibble(struct ranger_data* param_1, int param_2, enum room_id param_3);
void EnableTriggerSpawnNibble(struct ranger_data* param_1, int param_2, enum room_id param_3);
void UnlockPokemonSpawnNibble(struct ranger_data* param_1, int param_2, enum room_id param_3);
void EnablePokemonSpawnNibble(struct ranger_data* param_1, int param_2, enum room_id param_3);
undefined4 IsNpcSpawnNibbleUnlocked(struct ranger_data* param_1, int param_2, enum room_id param_3);
void UnlockNpcSpawnNibble(struct ranger_data* param_1, int param_2, enum room_id param_3);
void EnableNpcSpawnNibble(struct ranger_data* param_1, int param_2, enum room_id param_3);
undefined4 MaybeValidateFollowersAndParty(struct ranger_data_old* param_1, unsigned int param_2);
void MaybeHandleStylerLevelUp(struct ranger_data* param_1, unsigned int styler_level);
int CountValidPokemonInParty(struct ranger_data_old* param_1, int param_2);
int GetPartySizeSubtractPartner(struct ranger_data_old* param_1, undefined4 param_2, int param_3);
int CountNonPartnerPokemonInParty(struct ranger_data_old* param_1, int param_2);
bool HasPartnerPokemonInParty(struct ranger_data_old* param_1, int param_2);
int GetPartnerIndexInParty(struct ranger_data_old* param_1, int param_2);
void UpdatePlayTime(struct ranger_data* param_1);
void DebugPrint(char* fmt, ...);
void AssignPartnerMoods(struct ranger_data* param_1);
unsigned int GetStylerUpgradeById(struct ranger_data* param_1, int param_2);
void SetPlayerExp(struct ranger_data* param_1, uint32_t param_2);
int32_t AddPlayerExp(struct ranger_data* param_1, int32_t param_2);
void SetMaxStepsRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddMaxStepsRecord(struct ranger_data* param_1, int32_t param_2);
void SetConversationsRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddConversationsRecord(struct ranger_data* param_1, int32_t param_2);
void SetTargetsCheckedRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddTargetsCheckedRecord(struct ranger_data* param_1, int32_t param_2);
void SetGameSavesRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddGameSavesRecord(struct ranger_data* param_1, int32_t param_2);
void SetPokemonRidesRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddPokemonRidesRecord(struct ranger_data* param_1, int32_t param_2);
void SetPartnerPokemonBestnessIfGreaterByIndex(struct ranger_data* param_1, int param_2,
                                               unsigned int param_3);
int32_t IncrementPartnerPokeAssistsBySpecies(struct ranger_data* param_1, int16_t param_2,
                                             int param_3);
undefined2 MaybeGetBestPartnerRecord(struct ranger_data* param_1);
void SetCaptureLineLenRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddCaptureLineLenRecord(struct ranger_data* param_1, int32_t param_2);
void SetNumLoopsRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddNumLoopsRecord(struct ranger_data* param_1, int32_t param_2);
void SetPokemonCapturedRecord(struct ranger_data* param_1, int16_t param_2);
int16_t AddPokemonCapturedRecord(struct ranger_data* param_1, int16_t param_2);
void SetFledPokemonRecord(struct ranger_data* param_1, int16_t param_2);
int16_t AddFledPokemonRecord(struct ranger_data* param_1, int16_t pokemon_fled);
void SetPokeAssistsUsedRecord(struct ranger_data* param_1, int16_t param_2);
int16_t AddPokeAssistsUsedRecord(struct ranger_data* param_1, int16_t param_2);
bool CheckSaveFileValidity(void);
struct group_msg_wrapper_table* InitGroupMsgWrapperTable(struct group_msg_wrapper_table* param_1);
int FillPokemonNameMsgWrapper(struct group_msg_wrapper_table* param_1);
void ZeroPkmnNameMsgWrapper(struct group_msg_wrapper_table* param_1);
undefined4* FillItemNameMsgWrapper(struct group_msg_wrapper_table* param_1);
void ZeroItemNameMsgWrapper(struct group_msg_wrapper_table* param_1);
undefined4* FillTargetNameMsgWrapper(struct group_msg_wrapper_table* param_1);
void ZeroTargetNameMsgWrapper(struct group_msg_wrapper_table* param_1);
undefined4* FillNpcNameMsgWrapper(struct group_msg_wrapper_table* param_1);
void ZeroNpcNameMsgWrapper(struct group_msg_wrapper_table* param_1);
struct msg_wrapper* FillFieldMoveNameMsgWrapper(struct group_msg_wrapper_table* param_1);
void ZeroFieldMoveNameMsgWrapper(struct group_msg_wrapper_table* param_1);
char* GetPokemonNameById(struct group_msg_wrapper_table* param_1, int param_2);
char* GetItemNameById(struct group_msg_wrapper_table* param_1, int param_2);
char* GetTargetNameById(struct group_msg_wrapper_table* param_1, int param_2);
char* GetNpcNameById(struct group_msg_wrapper_table* param_1, int param_2);
char* GetFieldMoveNameById(struct group_msg_wrapper_table* param_1, int param_2);
void ZeroSettingsAndVariables(struct settings_and_variables* param_1);
void ZeroEventVariables(struct settings_and_variables* param_1);
void SetEventVariable(struct settings_and_variables* param_1, int32_t param_2, int32_t param_3);
int32_t GetEventVariable(struct settings_and_variables* param_1, int32_t param_2);
void ZeroQuestVariables(struct settings_and_variables* param_1);
void SetQuestVariable(struct settings_and_variables* param_1, int32_t param_2, int32_t param_3);
int32_t GetQuestVariable(struct settings_and_variables* param_1, int32_t param_2);
void SetSettingsVariable(struct settings_and_variables* param_1, int param_2, int32_t param_3);
int32_t GetSettingsVariable(struct settings_and_variables* param_1, int param_2);
void ret_0201a40c(void);
char* RetrieveStringIdFromMsgWrapperTable(struct msg_wrapper** param_1, uint32_t param_2);
void ret_020222c8(void);
void ret_020222cc(void);
void ret_020222d0(void);
void ret_020222d4(void);
void ret_02022710(void);
void ret_020228c0(void);
void ret_020237e0(void);
void ret_02029778(void);
void ret_0202a5f8(void);
undefined4 SysCallPrintTextbox(undefined4* param_1);
void SysCallIsTextboxPrinting(void);
undefined4 SysCallCloseTextbox(void);
undefined4 SysCallSetCustomTextSpeed(undefined4* param_1);
undefined4 SysCallSetDefaultTextSpeed(void);
undefined4 SysCallEnableAutoAdvanceTextWithDelay(undefined4* param_1);
undefined4 SysCallDisableAutoAdvanceText(void);
undefined4 SysCallEnableAutoCloseTextWithDelay(undefined4* param_1);
undefined4 SysCallDisableAutoCloseText(void);
void SysCallTryCloseTextbox(void);
void SysCallGetYesNoMenuResult(void);
void ret_0202d394(void);
void DebugPrintError(char* fmt, ...);
undefined4 SysCallCopyStringToRangerDebugBuffer(char** param_1);
undefined4 SysCallAddEnemyFormToEncounterType2(undefined4* param_1);
undefined4 SysCallBattleSetBgmId(undefined4* param_1);
undefined4 SysCallSetArenaGraphicId(undefined4* param_1);
int SysCallGetBattleResult(void);
undefined4 SysCallBattleDisableFleeing(void);
undefined4 SysCallBattleSetUnkField0x54(undefined4* param_1);
undefined4 SysCallBattleSetSequenceScriptId(undefined4* param_1);
undefined4 SysCallBattleSetTutorialScriptId(undefined4* param_1);
undefined4 SysCallBattleSetStartScriptId(undefined4* param_1);
undefined4 SysCallBattleSetStylerLevel(undefined4* param_1);
undefined4 SysCallBattleAddPartyPokemon(undefined4* param_1);
void SysCallAddEnemyFormToEncounterType1(undefined4* param_1);
undefined4 SysCallBattleSetGenderAndUniform(undefined4* param_1);
undefined4 SysCallBattleSetBossFightStatus(void);
undefined4 SysCallSetScriptSubroutine2ByName(undefined4* param_1, undefined4 param_2,
                                             undefined4 param_3, undefined4 param_4);
bool SysCallGetPlayerGender(void);
int8_t SysCallGetRangerStylerRank(void);
int32_t SysCallGetRangerStylerType(void);
int8_t SysCallGetStylerLevel(void);
undefined4 SysCallSetRangerCurrentHp(undefined4* param_1);
int8_t SysCallGetRangerMaxHp(void);
int8_t SysCallGetRangerCurrentHp(void);
void SysCallSetPlayerSpawnData(void* param_1, int param_2);
int8_t SysCallGetActiveMissionId(void);
undefined4 SysCallTryClearQuest(void);
void SysCallShouldShowQuestName(undefined4* param_1);
int8_t SysCallGetActiveQuestId(void);
undefined4 SysCallTryBackOutOfQuest(void);
undefined4 SysCallTryUnlockQuest(undefined4* param_1);
void SysCallIsQuestAvailable(undefined4* param_1);
undefined4 SysCallMakeQuestNameVisible(int* param_1);
void SysCallHasClearedQuest(undefined4* param_1);
int SysCallGetChapterNumber(void);
void SysCallGetQuestVariable(undefined4* param_1);
undefined4 SysCallSetQuestVariable(undefined4* param_1);
undefined4 SysCallEnableSlotStatusBit2(struct pokemon_data* param_1);
undefined4 SysCallDisableSlotStatusBit2(struct pokemon_data* param_1);
undefined4 SysCallEnableSlotStatusBit1(struct pokemon_data* param_1);
undefined4 SysCallDisableSlotStatusBit1(struct pokemon_data* param_1);
undefined4 SysCallBitorPartnerPokemonStatus(uint32_t* param_1);
uint32_t SysCallBitandPartnerPokemonStatus(uint32_t* param_1);
int8_t SysCallGetPartnerPokemonMood(int* param_1);
undefined4 SysCallBattleSetPartnerGaugeFillRate(undefined4* param_1);
void ret_02032a44(void);
void ret_0203331c(void);
void ret_02033388(void);
void ret_020333d8(void);
void ret_02033440(void);
void ret_0203365c(void);
void SysCallDisableActiveTimersAndMore(void);
void SysCallInitTimerType1(int32_t* param_1);
void SysCallInitTimerType2(int32_t* param_1);
void SysCallSetTimerTypeNone(void);
undefined4 SysCallSetTimerType1(void);
undefined4 SysCallSetTimerType2(void);
int32_t SysCallGetTimer1Duration(void);
undefined4 SysCallSetTimer1Duration(int32_t* param_1);
undefined4 SysCallTimerIsActive(void);
undefined4 SysCallIncrementPokemonRidesRecord(void);
int32_t SysCallGetGameSavesRecord(void);
struct script_data* InitScriptDataOuter(struct script_data* param_1);
undefined4 OpenAndInitScriptFile(struct script_data* param_1, char* param_2);
undefined4 OpenAndInitChXScript(struct script_data* param_1, struct script_file* param_2,
                                int param_3);
undefined4 SetScriptSubroutine1(struct script_data* param_1, char* param_2, undefined4 param_3,
                                undefined4 param_4);
void SetScriptSubroutine2(struct script_data* param_1, char* param_2, undefined4 param_3,
                          undefined4 param_4);
void ZeroInitScriptData(struct script_data* param_1);
void InitScriptData(struct script_data* param_1);
void MaybeCloseAndDeallocateScriptFile(struct script_data* param_1);
struct script_manager* InitScriptManagerOuter(struct script_manager* param_1, undefined4* param_2);
int TryInitSystemScript(struct script_manager* param_1, int param_2);
int TryInitAreaScript(struct script_manager* param_1, int param_2, undefined4 param_3,
                      undefined4 param_4);
int TryInitChapterScript(struct script_manager* param_1, int param_2, undefined4 param_3,
                         undefined4 param_4);
void TryInitQuestScript(struct script_manager* param_1, int param_2);
undefined4 SetScriptSubroutine1ByName(struct script_manager* param_1, char* param_2);
void SetScriptSubroutine2ByName(struct script_manager* param_1, char* param_2,
                                struct megastruct* param_3, undefined4 param_4);
void ZeroInitSystemScriptData(struct script_manager* param_1);
void ZeroInitAreaScriptData(struct script_manager* param_1);
void ZeroInitChapterScriptData(struct script_manager* param_1);
void ZeroInitQuestScriptData(struct script_manager* param_1);
void SetUnkRidingData(struct script_manager* param_1, undefined4 param_2);
undefined4 GetUnkRidingData(struct script_manager* param_1);
void ZeroInitAllScriptData(struct script_manager* param_1);
struct audio_engine* InitAudioEngineOuter(struct audio_engine* param_1);
bool IsFormIdPartnerPokemon(enum form_id param_1);
undefined4 GetPartnerIndexFromFormId(enum form_id param_1);
undefined4 GetPartnerIndexFromFormIdAgain(enum form_id param_1);
void ret_020358fc(void);
void ret_02035fe4(void);
void ret_0203e930(void);
void ret_0204078c(void);
void ret_0204129c(void);
void ret_02041920(void);
struct field_data* InitFieldData(struct field_data* param_1, char* param_2, undefined4 param_3);
void InitFieldFileData(struct field_data* param_1, char* param_2, int param_3);
void ret_02043124(void);
void ret_02043128(void);
void ret_020439c4(void);
void ret_020439c8(void);
void ret_02044144(void);
void ret_02044148(void);
void ret_020441ac(void);
void DebugPrintInternal(char* format, va_list ap);
void DebugPrintInternalVeneer(char* format, va_list ap);
void SetSysCallPageZero(void);
void UnpackScriptFile(struct script_file* param_1);
void SetSysCallPage(int param_1, void* param_2);
undefined4 SysCallReturnZero000(void);
undefined4 SysCallPrintStrWithPrefix(undefined4* param_1, undefined4 param_2, undefined4 param_3,
                                     undefined4 param_4);
undefined4 SysCallDebugPrintf(undefined4* param_1, undefined4 param_2, undefined4 param_3,
                              undefined4 param_4);
unsigned int SysCallFixedPointMultiply(int* param_1);
void SysCallFixedPointDivide(undefined4* param_1);
int SysCallGetTrigTableSin(unsigned int* param_1);
int SysCallGetTrigTableCos(unsigned int* param_1);
unsigned int SysCallGetTaylorPackedSinCos(undefined4* param_1);
unsigned int SysCallGetTaylorPackedCosSin(unsigned int* param_1);
unsigned int SysCallGetLcrngHigh(unsigned int* param_1);
unsigned int SysCallFixedPointRandomScale(int* param_1);
int SysCallFixedPointSignedRandomScale(int* param_1);
void SysCallSqrt32(undefined4* param_1);
void SysCallGetFixedPointReciprocal(undefined4* param_1);
void SysCallInverseSqrt(undefined4* param_1);
int SysCallFixedPointDegToRad(int* param_1);
unsigned int SysCallFixedPointRadToDeg(unsigned int* param_1);
void DegreesToFixedPointRotations(int* param_1);
undefined4 SysCallReturnZero047(void);
undefined4 SysCallReturnZero048(void);
undefined4 SysCallReturnZero049(void);
undefined4 SysCallReturnZero050(void);
undefined4 SysCallReturnZero051(void);
void SysCallGetFixedPointArcTanFromTable(undefined4* param_1);
void SysCallGetFixedPointArcTan2FromTable(undefined4* param_1);
undefined4 SysCallReturnZero052(void);
undefined4 SysCallReturnZero053(void);
undefined4 SysCallReturnZero054(void);
unsigned int SysCallFloorFixedPoint(unsigned int* param_1);
int SysCallAbs(int* param_1);
int SysCallIntToFixedPoint(int* param_1);
int SysCallFixedPointToInt(int* param_1);
void SysCallStrLen(undefined4* param_1);
undefined4 Wvr_StartUpAsync(int param_1, int param_2, undefined4 param_3);
undefined4 Wvr_TerminateAsync(int param_1, undefined4 param_2);
void WvrReceiveCallback(undefined4 param_1, unsigned int param_2);
void ret_02046d3c(void);
int32_t close(int32_t fd);
int32_t socket(int32_t domain, int32_t family, int32_t protocol);
int32_t bind(int32_t sockfd, const struct sockaddr_in* addr);
int32_t connect(int32_t sockfd, const struct sockaddr_in* addr);
int32_t recv(int32_t sockfd, void* buf, size_t size, int32_t flags);
int32_t recvfrom(int32_t sockfd, void* buf, size_t size, int32_t flags, struct sockaddr_in* addr,
                 int32_t addr_len);
int32_t send(int32_t sockfd, const void* buf, size_t size, int32_t flags);
int CloseVeneer(int _fd);
void ret_02049d08(void);
void GX_LoadBG0CharVeneer(void);
void GX_LoadBG1CharVeneer(void);
void GX_LoadBG2CharVeneer(void);
void GX_LoadBG3CharVeneer(void);
void GX_LoadBG0ScrVeneer(void);
void GX_LoadBG1ScrVeneer(void);
void GX_LoadBg2ScrVeneer(void);
void GX_LoadBg3ScrVeneer(void);
void GX_LoadObjPlttVeneer(void);
void GX_LoadBgPlttVeneer(void);
void GXs_LoadBg2ScrVeneer(void);
void GXs_LoadBg3ScrVeneer(void);
void InitSndAndMore(void);
void InitAudioSubstructFileData(struct unk_audio_engine_substruct_1* param_1, char* param_2,
                                void* param_3, int param_4);
void ret_0205fc98(void);
void ret_0205fcb8(void);
void MaybeLinearInterpolationInit(undefined4* param_1, undefined4 param_2, undefined4 param_3);
int MaybeLinearInterpolationProgress(int* param_1);
void MaybeLinearInterpolationUpdate(int param_1);
bool MaybeCheckIfLinearInterpolationMeetsThreshold(int param_1);
undefined4* Mtx_Identity22(undefined4* param_1);
undefined4* Mtx_Scale22(undefined4* param_1, undefined4 param_2, undefined4 param_3);
undefined4* Mtx_Identity33(undefined4* param_1);
void Mtx_RotZ33(undefined4* param_1, int param_2, undefined4 param_3);
undefined4* Mtx_Identity44(undefined4* param_1);
void Mtx_TransApply44(int* param_1, int* param_2, int param_3, int param_4, int param_5);
void Mtx_ScaleApply44(unsigned int* param_1, unsigned int* param_2, int param_3, int param_4,
                      int param_5);
undefined4* Mtx_RotZ44(undefined4* param_1, int param_2, undefined4 param_3);
void Mtx_Concat44(int* param_1, int* param_2, unsigned int* param_3, undefined4 param_4);
void Mtx_OrthoW(int param_1, int param_2, int param_3, int param_4, int param_5, int param_6,
                unsigned int param_7, int* param_8);
unsigned int FX_Div(int32_t param_1, int32_t param_2);
int64_t FX_DivFx64c(int32_t param_1, int32_t param_2);
int FX_Inv(int param_1);
int FX_Sqrt(int param_1);
int FX_InvSqrt(int param_1);
int64_t FX_GetInvResultFx64c(void);
unsigned int FX_GetDivResult(void);
void FX_InvAsync(int param_1);
void FX_SqrtAsync(int param_1);
unsigned int FX_GetSqrtResult(void);
void FX_DivAsync(int32_t param_1, int32_t param_2);
int FX_DivS32(int param_1, int param_2);
int FX_ModS32(int param_1, int param_2);
int64_t TaylorExpandFixedPointSin(unsigned int angle, int amplitude);
int64_t TaylorExpandFixedPointCos(unsigned int angle, int amplitude);
int64_t GetFixedPointSinCos(unsigned int param_1);
int64_t GetFixedPointCosSin(unsigned int param_1);
int FX_Atan(int param_1);
int FX_Atan2(int param_1, int param_2);
int16_t FX_Atan2Idx(int param_1, int param_2);
void ret_0206129c(void);
void GX_Init(void);
void GX_SetVCountEqVal(unsigned int param_1);
uint16_t GX_HBlankIntr(int param_1, uint16_t param_2);
uint16_t GX_VBlankIntr(int param_1, uint16_t param_2);
void GX_DispOff(void);
void GX_DispOn(void);
void GX_SetGraphicsMode(uint16_t param_1, unsigned int param_2, int param_3);
void GXs_SetGraphicsMode(unsigned int param_1);
void GXx_SetMasterBrightness(uint16_t* param_1, int param_2);
void GX_InitGxState(void);
void GX_VRamCnt_SetLcdc(unsigned int param_1);
void GX_SetBankForBG(int param_1);
void GX_SetBankForObj(int param_1);
void GX_SetBankForBgExtPltt(int param_1);
void GX_SetBankForObjExtPltt(int param_1);
void GX_SetBankForTex(int param_1);
void GX_SetBankForTexPltt(int param_1);
void GX_SetBankForClearImage(undefined4 param_1);
void GX_SetBankForArm7(int param_1);
void GX_SetBankForLcdc(uint16_t param_1);
void GX_SetBankForSubBg(int param_1);
void GX_SetBankForSubObj(int param_1);
void GX_SetBankForSubBgExtPltt(int param_1);
void GX_SetBankForSubObjExtPltt(int param_1);
uint16_t ResetBankForX(uint16_t* param_1);
void GX_ResetBankForBG(void);
void GX_ResetBankForObj(void);
void GX_ResetBankForBgExtPltt(void);
void GX_ResetBankForObjExtPltt(void);
void GX_ResetBankForTex(void);
void GX_ResetBankForTexPltt(void);
void GX_ResetBankForClearImage(void);
void GX_ResetBankForArm7(void);
void GX_ResetBankForSubBG(void);
void GX_ResetBankForSubObj(void);
void GX_ResetBankForSubBgExtPltt(void);
void GX_ResetBankForSubObjExtPltt(void);
uint16_t DisableBankForX(uint16_t* param_1);
void GX_DisableBankForBg(void);
void GX_DisableBankForObj(void);
void GX_DisableBankForBgExtPltt(void);
void GX_DisableBankForObjExtPltt(void);
void GX_DisableBankForTex(void);
void GX_DisableBankForTexPltt(void);
void GX_DisableBankForClearImage(void);
void GX_DisableBankForArm7(void);
void GX_DisableBankForLcdc(void);
void GX_DisableBankForSubBg(void);
void GX_DisableBankForSubObj(void);
void GX_DisableBankForSubBgExtPltt(void);
void GX_DisableBankForSubObjExtPltt(void);
undefined2 GX_GetBankForBg(void);
undefined2 GX_GetBankForObj(void);
undefined2 GX_GetBankForBgExtPltt(void);
int G2_GetBg0ScrPtr(void);
int G2S_GetBg0ScrPtr(void);
int G2_GetBg1ScrPtr(void);
int G2S_GetBg1ScrPtr(void);
int G2_GetBg2ScrPtr(void);
int G2S_GetBg2ScrPtr(void);
int G2_GetBg3ScrPtr(void);
int G2S_GetBg3ScrPtr(void);
int G2_GetBg0CharPtr(void);
int G2S_GetBg0CharPtr(void);
int G2_GetBg1CharPtr(void);
int G2S_GetBg1CharPtr(void);
int G2_GetBg2CharPtr(void);
int G2S_GetBg2CharPtr(void);
int G2_GetBg3CharPtr(void);
int G2S_GetBg3CharPtr(void);
void G2x_SetBgyAffine(unsigned int* param_1, int* param_2, int param_3, int param_4, int param_5,
                      int param_6);
void G2x_SetBlendAlpha(unsigned int* param_1, unsigned int param_2, int param_3,
                       unsigned int param_4, int param_5);
void G2x_SetBlendBrightness(uint16_t* param_1, uint16_t param_2, int param_3);
void G2x_ChangeBlendBrightness(uint16_t* param_1, int param_2);
void G3C_Direct0(unsigned int* param_1, int param_2);
void G3C_Direct1(undefined4* param_1, undefined1 param_2, undefined4 param_3);
void G3C_Direct2(undefined4* param_1, undefined1 param_2, undefined4 param_3, undefined4 param_4);
void G3C_UpdateGxDlInfo(unsigned int* param_1, int param_2);
void G3C_PopMtx(undefined4 param_1, undefined4 param_2);
void G3C_Color(undefined4 param_1, undefined4 param_2);
void G3C_TexCoord(undefined4 param_1, int param_2, int param_3);
void G3C_Vtx(undefined4 param_1, unsigned int param_2, int param_3, undefined2 param_4);
void G3C_VtxXY(undefined4 param_1, unsigned int param_2, int param_3);
void G3C_PolygonAttr(undefined4 param_1, unsigned int param_2, int param_3, int param_4,
                     int param_5, int param_6, unsigned int param_7);
void G3C_TexImageParam(undefined4 param_1, int param_2, int param_3, int param_4, int param_5,
                       int param_6, int param_7, int param_8, unsigned int param_9);
void G3C_TexPlttBase(undefined4 param_1, unsigned int param_2, int param_3);
void G3C_Begin(undefined4 param_1, undefined4 param_2);
void G3C_End(undefined4 param_1);
void G3_LoadMtx44(void);
void G3_LoadMtx43(void);
void G3X_Init(void);
void G3X_Reset(void);
void G3X_ClearFifo(void);
void G3X_InitMtxStack(void);
void G3X_ResetMtxStack(void);
void G3X_SetToonTable(undefined4 param_1);
void G3X_SetClearColor(unsigned int param_1, int param_2, undefined2 param_3, int param_4,
                       int param_5);
void G3X_InitTable(void);
undefined4 G3X_GetMtxStackLevelPV(unsigned int* param_1);
undefined4 G3X_GetMtxStackLevelPJ(unsigned int* param_1);
void GXi_NopClearFifo128(undefined4* param_1);
void G3i_OrthoW(int param_1, int param_2, int param_3, int param_4, int param_5, int param_6,
                unsigned int param_7, int param_8, int* param_9);
void G3_LoadTexMtxTexCoord(undefined4* param_1);
void GXs_LoadBgPltt(int param_1, int param_2, unsigned int param_3, undefined4 param_4);
void GX_LoadObjPltt(int param_1, int param_2, unsigned int param_3, undefined4 param_4);
void GXs_LoadObjPltt(int param_1, int param_2, unsigned int param_3, undefined4 param_4);
void GX_LoadOam(undefined4 param_1, int param_2, unsigned int param_3);
void GXs_LoadOam(undefined4 param_1, int param_2, unsigned int param_3, undefined4 param_4);
void GX_LoadObj(undefined4 param_1, int param_2, unsigned int param_3);
void GXs_LoadObj(undefined4 param_1, int param_2, unsigned int param_3);
void GX_LoadBg0Scr(int param_1, int param_2, unsigned int param_3);
void GXs_LoadBg0Scr(int param_1, int param_2, unsigned int param_3);
void GX_LoadBg1Scr(int param_1, int param_2, unsigned int param_3);
void GXs_LoadBg1Scr(int param_1, int param_2, unsigned int param_3);
void GX_LoadBg0Char(undefined4 param_1, int param_2, unsigned int param_3);
void GXs_LoadBg0Char(undefined4 param_1, int param_2, unsigned int param_3);
void GX_LoadBg1Char(undefined4 param_1, int param_2, unsigned int param_3);
void GXs_LoadBg1Char(undefined4 param_1, int param_2, unsigned int param_3);
void GX_LoadBg2Char(undefined4 param_1, int param_2, unsigned int param_3);
void GXs_LoadBg2Char(undefined4 param_1, int param_2, unsigned int param_3);
void GX_LoadBg3Char(undefined4 param_1, int param_2, unsigned int param_3);
void GXs_LoadBg3Char(undefined4 param_1, int param_2, unsigned int param_3);
void GX_BeginLoadBgExtPltt(void);
void GX_LoadBgExtPltt(undefined4 param_1, int param_2, undefined4 param_3, undefined4 param_4);
void GX_EndLoadBgExtPltt(void);
void GX_BeginLoadObjExtPltt(void);
void GX_LoadObjExtPltt(undefined4 param_1, int param_2, undefined4 param_3);
void GX_EndLoadObjExtPltt(void);
void GXs_BeginLoadBgExtPltt(void);
void GXs_LoadBgExtPltt(undefined4 param_1, int param_2, undefined4 param_3);
void GXs_EndLoadBgExtPltt(void);
void GXs_BeginLoadObjExtPltt(void);
void GXs_LoadObjExtPltt(undefined4 param_1, int param_2, undefined4 param_3);
void GXs_EndLoadObjExtPltt(void);
void GX_BeginLoadTex(void);
void GX_LoadTex(int param_1, unsigned int param_2, int param_3, undefined4 param_4);
void GX_EndLoadTex(void);
void GX_BeginLoadTexPltt(void);
void GXi_DmaCopy32Async(undefined4 param_1, int param_2, undefined4 param_3);
void GX_EndLoadTexPltt(void);
void GX_BeginLoadClearImage(void);
void GX_LoadClearImageColor(undefined4 param_1, undefined4 param_2);
void GX_LoadClearImageDepth(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                            undefined4 param_4);
void GX_EndLoadClearImage(void);
undefined4* GX_SendFifo64B(undefined4* param_1, undefined4* param_2);
void OS_WaitIrq(int param_1, unsigned int param_2);
void ret_020647a0(void);
void OSi_IrqCallback(int param_1);
void OSi_IrqDma0(void);
void OSi_IrqDma1(void);
void OSi_IrqDma2(void);
void OSi_IrqDma3(void);
void OSi_IrqTimer0(void);
void OSi_IrqTimer1(void);
void OSi_IrqTimer2(void);
void OSi_IrqTimer3(void);
void OS_InitIrqTable(void);
void OS_SetIrqFunction(uint32_t intr_bit, os_irq_function function);
undefined4 OS_GetIrqFunction(unsigned int param_1);
void OSi_EnterDmaCallback(int param_1, undefined4 param_2, undefined4 param_3);
void OSi_EnterTimerCallback(int param_1, undefined4 param_2, undefined4 param_3);
uint32_t OS_SetIrqMask(uint32_t mask);
uint32_t OS_EnableIrqMask(uint32_t mask);
uint32_t OS_DisableIrqMask(uint32_t mask);
uint32_t OS_ResetRequestIrqMask(uint32_t mask);
void OS_SetIrqStackChecker(void);
void OS_InitLock(void);
void OSi_DoLockByWord(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                      undefined4 param_4);
int32_t OS_LockByWord(uint16_t lock_id, struct os_lock_word* lockp, lock_ctrl_funcp ctrl_funcp);
undefined4 OSi_DoUnlockByWord(unsigned int param_1, undefined4* param_2, void** param_3,
                              int param_4);
int32_t OS_UnlockByWord(uint16_t lock_id, struct os_lock_word* lockp, lock_ctrl_funcp ctrl_funcp);
int OSi_DoTryLockByWord(undefined4 param_1, int param_2, void** param_3, int param_4);
undefined4 OS_LockCartridge(undefined4 param_1);
int32_t OS_UnlockCartridge(uint16_t lock_id);
int32_t OS_UnlockCartridgeVeneer(uint16_t lock_id);
undefined4 OS_TryLockCartridge(undefined4 param_1);
void OSi_LockCardID(void);
void OSi_UnlockCardID(void);
void OS_LockCard(undefined4 param_1);
void OS_UnlockCard(undefined4 param_1);
void OSi_AllocateCardBus(void);
void OSi_FreeCardBus(void);
undefined2 OS_ReadOwnerOfLockWord(int param_1);
int32_t OS_GetLockID(void);
void OS_ReleaseLockID(int param_1);
void MaybeCopyFileName(char* param_1, char* param_2, undefined4 param_3, undefined4 param_4);
void OS_VsPrintf(undefined4 param_1, undefined4 param_2, undefined4 param_3);
void OS_SnPrintf(undefined1* param_1, int param_2, int8_t* param_3, unsigned int param_4);
int OS_VsNPrintf(undefined1* param_1, int param_2, int8_t* param_3, unsigned int* param_4);
void OS_VsNPrintfExStub(void);
void OSi_GetUnusedThreadId(void);
void OSi_InsertLinkToQueue(struct os_thread_queue* queue, struct thread* thread);
int OSi_RemoveLinkFromQueue(int* param_1);
int OSi_RemoveSpecifiedLinkFromQueue(int* param_1, int param_2);
int OSi_RemoveMutexLinkFromQueue(int* param_1);
void OSi_InsertThreadToList(struct thread* thread);
void OSi_RemoveThreadFromList(int param_1);
void OSi_RescheduleThread(void);
void OS_InitThread(void);
undefined4 OS_IsThreadAvailable(void);
void OS_CreateThread(struct thread* param_1, undefined4 param_2, uint32_t param_3, void* param_4,
                     int param_5, int param_6);
void OS_ExitThread(void);
void OSi_ExitThread_ArgSpecified(unsigned int* param_1, unsigned int param_2, undefined4 param_3,
                                 undefined4 param_4);
void OSi_ExitThread(void);
void OSi_ExitThread_Destroy(void);
void OS_DestroyThread(int param_1);
void OSi_CancelThreadAlarmForSleep(int param_1);
void OS_JoinThread(struct thread* param_1);
bool OS_IsThreadTerminated(int param_1);
void OS_SleepThread(struct os_thread_queue* queue);
void OS_WakeupThread(int* param_1);
void OS_WakeupThreadDirect(struct thread* thread);
void OS_SelectThread(undefined4 param_1, int param_2);
void OS_RescheduleThread(void);
void OS_YieldThread(void);
undefined4 OS_SetThreadPriority(undefined* param_1, int param_2);
undefined4 OS_GetThreadPriority(int param_1);
void OS_Sleep(unsigned int param_1);
void OSi_SleepAlarmCallback(int* param_1);
os_switch_thread_callback OS_SetSwitchThreadCallback(os_switch_thread_callback callback);
void OSi_IdleThreadProc(void* arg);
int OS_DisableScheduler(void);
int OS_EnableScheduler(void);
void OS_SetThreadDestructor(struct thread* thread, int32_t value);
void OS_InitContext(undefined4* param_1, int param_2, int param_3);
bool OS_SaveContext(struct os_context* context);
void OS_LoadContext(struct os_context* context);
undefined4 OS_IsRunOnEmulator(void);
void OS_GetConsoleType(void);
void OS_InitMessageQueue(undefined4* param_1, undefined4 param_2, undefined4 param_3);
undefined4 OS_SendMessage(int param_1, undefined4 param_2, unsigned int param_3);
undefined4 OS_ReceiveMessage(int param_1, undefined4* param_2, unsigned int param_3);
undefined4 OS_JamMessage(int param_1, undefined4 param_2, unsigned int param_3);
undefined4 OS_ReadMessage(int param_1, undefined4* param_2, unsigned int param_3);
void OS_InitMutex(struct os_mutex* mutex);
bool OS_LockMutex(undefined4* param_1, int param_2);
void OS_UnlockMutex(int param_1);
void OSi_UnlockAllMutex(int param_1);
undefined4 OS_TryLockMutex(int param_1);
void OSi_EnqueueTail(int param_1, int param_2);
void OSi_DequeueItem(int param_1, int param_2);
undefined4 DC_InvalidateAll(void);
void DC_Store_All(void);
void DC_FlushAll(void);
void DC_InvalidateRange(void* start_addr, uint32_t n_bytes);
void DC_StoreRange(unsigned int param_1, int param_2);
void DC_FlushRange(void* data, uint32_t size);
undefined4 DC_WaitWriteBufferEmpty(void);
undefined4 IC_InvalidateAll(void);
void IC_InvalidateRange(unsigned int param_1, int param_2);
void OSi_WaitVCount0(void);
void OS_Init(void);
void OS_InitArena(void);
void OS_InitArenaEx(void);
void* OS_GetArenaHi(int param_1);
void* OS_GetArenaLo(int param_1);
void* OS_GetInitArenaHi(int param_1);
void* OS_GetInitArenaLo(enum os_arena_id id);
void OS_SetArenaHi(enum os_arena_id id, void* new_hi);
void OS_SetArenaLo(enum os_arena_id id, void* new_lo);
void* OS_AllocFromArenaLo(int param_1, int param_2, int param_3);
unsigned int OS_GetDtcmAddress(void);
unsigned int OS_EnableProtectionUnit(void);
unsigned int OS_DisableProtectionUnit(void);
void OS_SetDPermissionsForProtectionRegion(unsigned int param_1, unsigned int param_2);
void OS_SetProtectionRegion1(uint32_t param);
void OS_SetProtectionRegion2(uint32_t param);
void OS_InitException(void);
void OSi_ExceptionHandler(void);
undefined4 OSi_GetAndDisplayContext(undefined4 param_1);
int OSi_SetExContext(undefined4 param_1);
void OSi_DisplayExContext(void);
void OSi_DisplayExContext_Helper(void);
void OSi_SetTimerReserved(unsigned int param_1);
void OSi_UnsetTimerReserved(unsigned int param_1);
void OS_InitTick(void);
bool OS_IsTickAvailable(void);
void OSi_CountUpTick(void);
int64_t OS_GetTick(void);
undefined2 OS_GetTickLo(void);
void OSi_SetTimer(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void OS_InitAlarm(void);
void OS_EndAlarm(void);
undefined2 OS_IsAlarmAvailable(void);
void OS_CreateAlarm(undefined4* param_1);
void OSi_InsertAlarm(int param_1, undefined4 param_2, undefined4 param_3);
void OS_SetAlarm(int* param_1, undefined4 param_2, undefined4 param_3, int param_4, int param_5);
void OS_CancelAlarm(int* param_1);
undefined4 OSi_AlarmHandler(undefined4 param_1);
void OSi_ArrangeTimer(void);
void OS_InitVAlarm(void);
void OS_EndVAlarm(void);
void OSi_InsertVAlarm(int param_1);
void OSi_AppendVAlarm(int param_1);
void OSi_DetachVAlarm(int param_1);
void OS_CreateVAlarm(undefined4* param_1);
void OS_SetVAlarm(int* param_1, int param_2, undefined2 param_3, int param_4, int param_5);
void OS_SetPeriodicVAlarm(int* param_1, int param_2, undefined2 param_3, int param_4, int param_5);
void OSi_SetNextVAlarm(int param_1);
void OS_CancelVAlarm(int* param_1);
void OS_CancelAllVAlarms(void);
void OSi_VAlarmHandler(void);
undefined4 OSi_CompareVCount(int param_1, int param_2, int param_3);
undefined4 OSi_GetVFrame(int param_1);
long long OS_EnableInterrupts(void);
int32_t OS_DisableInterrupts(void);
int32_t OS_RestoreInterrupts(int32_t new_value);
long long OS_EnableInterrupts_IrqAndFiq(void);
undefined4 OS_RestoreInterrupts_IrqAndFiq(void);
undefined4 OS_GetCpsrIrq(void);
undefined4 OS_GetProcMode(void);
void OS_SpinWait(unsigned int param_1);
void OS_WaitVBlankIntr(void);
void OS_InitReset(void);
void OSi_CommonCallback(undefined4 param_1, unsigned int param_2);
void OSi_SendToPxi(uint16_t param_1);
void OS_ResetSystem(undefined4 param_1);
void OS_GetMacAddress(uint8_t* macAddress);
void OS_GetOwnerInfo(struct user_settings* settings);
uint32_t Math_CountLeadingZeros(uint32_t x);
void OSi_InitVramExclusive(void);
bool OSi_TryLockVram(uint16_t param_1, uint16_t param_2);
void OSi_UnlockVram(uint16_t param_1, uint16_t param_2);
void OS_GetLowEntropyData(unsigned int* param_1);
void OS_Panic(void);
void OS_Halt(void);
void MI_SetWramBank(enum mi_wram cnt);
void MI_DmaFill32(int param_1, undefined4 param_2, undefined4 param_3, unsigned int param_4);
void MI_DmaSend32(int param_1, undefined4 param_2, undefined4 param_3, unsigned int param_4);
void MI_DmaFill16(int param_1, undefined4 param_2, undefined4 param_3, unsigned int param_4);
void MI_DmaCopy16(uint32_t dma_no, void* src, void* dest, uint32_t size);
void MI_DmaFill32Async(int param_1, undefined4 param_2, undefined4 param_3, unsigned int param_4,
                       void** param_5, undefined4 param_6);
void MI_DmaCopy32Async(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                       unsigned int param_4, void** param_5, undefined4 param_6);
void MI_WaitDma(int param_1);
void MI_StopDma(uint32_t dma_no);
void MIi_CheckAnotherAutoDma(int param_1, unsigned int param_2);
void MIi_CheckDma0SourceAddress(uint32_t dma_no, uint32_t src, uint32_t size, uint32_t dir);
void MIi_CpuClear16(uint16_t val, void* ptr, int32_t len);
void MIi_CpuCopy16(void* src, void* dest, int32_t len);
void MIi_CpuClear32(uint32_t val, void* ptr, int32_t len);
void MIi_CpuCopy32(void* src, void* dest, int32_t len);
void MIi_CpuClearFast(uint32_t val, void* ptr, int32_t len);
void MIi_CpuCopyFast(void* src, void* dest, int32_t len);
int64_t MI_Copy36B(undefined4* param_1, undefined4* param_2);
int64_t MI_Copy48B(undefined4* param_1, undefined4* param_2);
void MI_CpuFill8(void* ptr, char val, uint32_t len);
void MI_CpuCopy8(void* src, void* dest, uint32_t n);
undefined4 MI_SwapWord(undefined4 param_1, undefined4* param_2);
void MI_UncompressLZ8(unsigned int* param_1, int8_t* param_2);
void MI_UncompressHuffman(unsigned int* param_1, unsigned int* param_2);
void MI_UncompressRL8(unsigned int* param_1, int8_t* param_2);
void MI_UnfilterDiff8(unsigned int* param_1, int param_2);
void MIi_CardDmaCopy32(int param_1, undefined4 param_2, undefined4 param_3, int param_4);
void MI_Init(void);
void Snd_StopSeq(undefined4 param_1);
void Snd_PrepareSeq(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Snd_StartPreparedSeq(undefined4 param_1);
void Snd_SetPlayerTempoRatio(undefined4 param_1, undefined4 param_2);
void Snd_SetPlayerVolume(undefined4 param_1, undefined4 param_2);
void Snd_SetPlayerChannelPriority(undefined4 param_1, undefined4 param_2);
void Snd_SetTrackPan(undefined4 param_1, undefined4 param_2, undefined4 param_3);
void Snd_SetTrackAllocatableChannel(undefined4 param_1, undefined4 param_2, undefined4 param_3);
void Snd_StartTimer(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Snd_StopTimer(undefined4 param_1, undefined4 param_2, unsigned int param_3,
                   undefined4 param_4);
void Snd_SetupAlarm(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4,
                    undefined4 param_5);
void Snd_LockChannel(undefined4 param_1, undefined4 param_2);
void Snd_UnlockChannel(undefined4 param_1, undefined4 param_2);
void Snd_SetChannelVolume(undefined4 param_1, undefined4 param_2, undefined4 param_3);
void Snd_SetChannelPan(undefined4 param_1, undefined4 param_2);
void Snd_SetupChannelPcm(unsigned int param_1, int param_2, undefined4 param_3, int param_4,
                         unsigned int param_5, unsigned int param_6, int param_7, int param_8,
                         int param_9, int param_10);
void Snd_InvalidateSeqData(undefined4 param_1, undefined4 param_2);
void Snd_InvalidateBankData(undefined4 param_1, undefined4 param_2);
void Snd_InvalidateWaveData(undefined4 param_1, undefined4 param_2);
void Snd_SetOutputSelector(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                           undefined4 param_4);
void Sndi_SetPlayerParam(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                         undefined4 param_4);
void Sndi_SetTrackParam(unsigned int param_1, undefined4 param_2, undefined4 param_3,
                        undefined4 param_4, int param_5);
void PushCommand_Impl(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                      undefined4 param_4, undefined4 param_5);
void Snd_Init(void);
bool Sndi_LockMutex(undefined4 param_1);
void Sndi_UnlockMutex(void);
void Snd_CommandInit(void);
int* Snd_RecvCommandReply(unsigned int param_1);
void Snd_AllocCommand(unsigned int param_1);
void Snd_PushCommand(undefined4* param_1);
undefined4 Snd_FlushCommand(unsigned int param_1);
void Snd_WaitForCommandProc(undefined4 param_1);
undefined4 Snd_GetCurrentCommandTag(void);
bool Snd_IsFinishedCommandTag(unsigned int param_1);
int Snd_CountFreeCommand(void);
int Snd_CountReservedCommand(void);
int Snd_CountWaitingCommand(void);
void PxiFifoCallback(undefined4 param_1, undefined4 param_2);
void InitPxi(void);
void RequestCommandProc(void);
int* AllocCommand(void);
bool IsCommandAvailable(void);
void Snd_AlarmInit(void);
void Sndi_IncAlarmId(int param_1);
char Sndi_SetAlarmHandler(int param_1, undefined4 param_2, undefined4 param_3);
void Sndi_CallAlarmHandler(unsigned int param_1);
undefined4 Snd_GetPlayerStatus(void);
undefined4 Sndi_GetFinishedCommandTag(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                                      undefined4 param_4);
void Sndi_InitSharedWork(undefined4* param_1);
uint16_t Snd_CalcChannelVolume(int32_t value);
void Snd_AssignWaveArc(int param_1, int param_2, int param_3);
void Snd_DestroyBank(int param_1, undefined4 param_2);
void Snd_DestroyWaveArc(int param_1, undefined4 param_2);
void Snd_GetFirstInstDataPos(undefined4* param_1);
undefined4 Snd_GetNextInstData(int param_1, undefined2* param_2, unsigned int* param_3);
undefined4 Snd_GetWaveDataCount(int param_1);
void Snd_SetWaveDataAddress(int param_1, int param_2, undefined4 param_3);
unsigned int Snd_GetWaveDataAddress(int param_1, int param_2);
void Pxi_Init(void);
void Pxi_InitFifo(void);
void Pxi_SetFifoRecvCallback(int32_t fifo_tag, pxi_fifo_callback callback);
void Pxi_IsCallbackReady(int32_t fifo_tag, enum pxi_proc proc);
int32_t Pxi_SendWordByFifo(int32_t fifo_tag, uint32_t data, bool err);
void Pxii_HandlerRecvFifoNotEmpty(void);
void FSi_ReleaseCommand(int* param_1, int param_2);
int FSi_TranslateCommand(int param_1, unsigned int param_2);
int FSi_StrNiCmp(int param_1, int param_2, unsigned int param_3);
unsigned int FSi_ReadTable(int* param_1, undefined4 param_2, int param_3, undefined4 param_4);
void FSi_SeekDirDirect(int param_1, undefined2 param_2);
undefined4 FSi_ReadFileCommand(int param_1);
undefined4 FSi_WriteFileCommand(int param_1);
int FSi_SeekDirCommand(int param_1);
int FSi_ReadDirCommand(int param_1);
undefined4 FSi_FindPathCommand(int param_1, undefined4 param_2, undefined4 param_3,
                               undefined4 param_4);
undefined4 FSi_GetPathCommand(int param_1, undefined4 param_2, undefined4 param_3,
                              undefined4 param_4);
int FSi_OpenFileFastCommand(int param_1, undefined4 param_2, undefined4 param_3,
                            undefined4 param_4);
undefined4 FSi_OpenFileDirectCommand(int param_1);
undefined4 FSi_CloseFileCommand(void);
unsigned int FSi_GetPackedName(int param_1, int param_2);
undefined4 FSi_ReadMemCallback(int param_1, undefined4* param_2, int param_3, unsigned int param_4);
undefined4 FSi_WriteMemCallback(int param_1, undefined4* param_2, int param_3,
                                unsigned int param_4);
undefined4 FSi_ReadMemoryCore(undefined4 param_1, undefined4* param_2, undefined4* param_3,
                              unsigned int param_4);
int FSi_NextCommand(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void FSi_ExecuteAsyncCommand(int param_1);
bool FSi_ExecuteSyncCommand(int param_1);
undefined4 FSi_SendCommand(int* param_1, unsigned int param_2);
void FS_InitArchive(int8_t* param_1);
int* FS_FindArchive(void);
undefined4 FS_RegisterArchiveName(undefined4* param_1, undefined4 param_2, undefined4 param_3);
void FS_ReleaseArchiveName(int* param_1);
undefined4 FS_LoadArchive(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4,
                          undefined4 param_5, undefined4 param_6, undefined* param_7,
                          undefined* param_8);
undefined4 FS_UnloadArchive(int param_1);
unsigned int FS_LoadArchiveTables(int param_1, int param_2, unsigned int param_3);
undefined4 FS_UnloadArchiveTables(int param_1);
bool FS_SuspendArchive(int param_1);
bool FS_ResumeArchive(int param_1);
void FS_SetArchiveProc(int param_1, int param_2, int param_3);
void FS_NotifyArchiveAsyncEnd(int param_1, undefined4 param_2);
void FS_Init(void);
void FS_InitFile(undefined4* param_1);
void FSi_FindPath(int param_1, char* param_2, undefined4 param_3, int param_4);
int FSi_ReadFileCore(int param_1, undefined4 param_2, int param_3, int param_4);
bool FS_ConvertPathToFileID(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                            undefined4 param_4);
undefined4 FS_OpenFileDirect(int param_1, undefined4 param_2, undefined4 param_3,
                             undefined4 param_4, undefined4 param_5);
undefined4 FS_OpenFileFast(int param_1, int param_2, undefined4 param_3);
undefined4 FS_OpenFile(undefined4 param_1);
undefined4 FS_CloseFile(int param_1);
unsigned int FS_WaitAsync(int param_1);
void FS_CancelFile(int param_1);
void FS_ReadFile(void);
undefined4 FS_SeekFile(int param_1, int param_2, int param_3);
undefined4 FS_ChangeDir(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                        undefined4 param_4);
void FSi_OnRomReadDone(undefined4 param_1);
undefined4 FSi_ReadRomCallback(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                               undefined4 param_4);
undefined4 FSi_WriteDummyCallback(void);
undefined4 FSi_RomArchiveProc(undefined4 param_1, int param_2);
undefined4 FSi_ReadDummyCallback(void);
undefined4 FSi_EmptyArchiveProc(void);
void FSi_InitRom(undefined4 param_1);
undefined4 FS_SetDefaultDma(undefined4 param_1);
unsigned int FSi_GetOverlayBinarySize(int param_1);
void FS_ClearOverlayImage(int param_1);
void FS_GetOverlayFileID(undefined4* param_1, int param_2);
undefined4 FSi_LoadOverlayInfoCore(int param_1, int param_2, int param_3, undefined4 param_4,
                                   int param_5, unsigned int param_6, int param_7,
                                   unsigned int param_8);
undefined4 FS_LoadOverlayInfo(undefined4* param_1, int param_2, int param_3, undefined4 param_4);
undefined4 FS_LoadOverlayImage(int param_1, undefined4 param_2, undefined4 param_3,
                               undefined4 param_4);
bool FSi_CompareOverlayDigest(int param_1, undefined4 param_2, undefined4 param_3);
void FS_StartOverlay(unsigned int* param_1, undefined4 param_2, undefined4 param_3,
                     undefined4 param_4);
void FS_EndOverlay(int param_1);
undefined4 FS_UnloadOverlayImage(void);
undefined4 FS_LoadOverlay(undefined4 param_1, undefined4 param_2);
undefined4 FS_UnloadOverlay(undefined4 param_1, undefined4 param_2);
void Math_MD5Init(undefined4* param_1);
void Math_MD5Update(int param_1, undefined4* param_2, unsigned int param_3);
void Math_MD5GetHash(undefined4* param_1, int8_t* param_2, undefined4 param_3, undefined4 param_4);
void Math_MD5Transform(unsigned int* param_1);
void Dgt_Hash2Init(undefined4* param_1);
void Dgt_Hash2Update(int param_1, undefined4* param_2, unsigned int param_3, undefined4 param_4);
void Dgt_Hash2GetHash(undefined4* param_1, undefined1* param_2, undefined4 param_3,
                      undefined4 param_4);
void Dgt_Hash2CalcHmac(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                       undefined4 param_4, undefined4 param_5);
void Dgti_CalcHmac(int param_1, int param_2, int param_3, int8_t***** param_4, int param_5,
                   int* param_6);
void Dgt_Hash2Transform(unsigned int* param_1, unsigned int* param_2, int param_3);
void CP_SaveContext(undefined4* param_1);
void CPi_RestoreContext(undefined4* param_1);
void TPi_TpCallback(undefined4 param_1, unsigned int param_2, int param_3);
void TP_Init(void);
void TP_GetUserInfo(undefined* param_1);
void TP_SetCalibrateParam(int16_t* param_1);
void TP_RequestSamplingAsync(void);
undefined4 TP_WaitRawResult(undefined2* param_1);
void TP_RequestAutoSamplingStartAsync(unsigned int param_1, unsigned int param_2,
                                      undefined4 param_3, unsigned int param_4);
void TP_RequestSetStabilityAsync(void);
undefined2 TP_GetLatestIndexInAuto(void);
undefined2* TP_CalcCalibrateParam(undefined2* param_1, undefined2* param_2, unsigned int param_3,
                                  unsigned int param_4, uint16_t param_5, uint16_t param_6,
                                  uint16_t param_7, uint16_t param_8, uint16_t param_9);
void TP_GetCalibratedPoint(uint16_t* param_1, uint16_t* param_2);
void TP_WaitBusy(uint16_t param_1);
uint16_t TP_CheckBusy(uint16_t param_1);
undefined4 PMi_Lock(void);
void PMi_WaitBusy(void);
void PMi_DummyCallback(undefined4 param_1, undefined4* param_2);
void PMi_CallCallbackAndUnlock(void);
void PM_Init(void);
void PMi_CommonCallback(void);
undefined4 PMi_SendSleepStart(unsigned int param_1, unsigned int param_2);
undefined4 PM_SendUtilityCommandAsync(unsigned int param_1, undefined4 param_2, undefined4 param_3);
undefined4 PMi_ReadRegisterAsync(unsigned int param_1, undefined4 param_2, undefined4 param_3,
                                 undefined4 param_4);
int PMi_ReadRegister(uint16_t param_1, uint16_t* param_2);
void PMi_SetLedAsync(int param_1, undefined4 param_2, undefined4 param_3);
int PMi_SetLed(undefined4 param_1, undefined4 param_2, undefined4 param_3, int param_4);
undefined4 PM_SetBackLightAsync(int param_1, int param_2, undefined4 param_3, undefined4 param_4);
int PM_SetBackLight(undefined4 param_1, undefined4 param_2);
void PM_ForceToPowerOffAsync(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                             undefined4 param_4);
uint32_t PM_ForceToPowerOff(void);
void PM_GetBackLight(unsigned int* param_1, unsigned int* param_2, undefined4 param_3,
                     unsigned int param_4);
void PMi_SendPxiData(undefined4 param_1);
void PM_GoSleepMode(unsigned int param_1, uint16_t param_2, uint16_t param_3, undefined4 param_4);
undefined4 PMi_SetLcdPower(int param_1, int param_2, int param_3, int param_4);
void PM_SetLcdPower(int param_1);
bool PM_GetLcdPower(void);
undefined4 PMi_SendLedPatternCommandAsync(unsigned int param_1, undefined4 param_2,
                                          undefined4 param_3);
int PMi_SendLedPatternCommand(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                              int param_4);
undefined4 PM_GetLedPatternAsync(undefined4 param_1, undefined4 param_2, undefined4 param_3);
undefined4 PM_GetLedPattern(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                            undefined4 param_4);
void PMi_PrependList(int* param_1, int param_2);
void PMi_AppendList(int* param_1, int param_2);
void PMi_DeleteList(int* param_1, int param_2, int param_3, int param_4);
void PMi_ExecuteList(undefined4* param_1);
void PM_PrependPreSleepCallback(undefined4 param_1);
void PM_AppendPostSleepCallback(undefined4 param_1);
void PM_DeletePreSleepCallback(undefined4 param_1);
void PM_DeletePostSleepCallback(undefined4 param_1);
void Rtc_Init(void);
undefined4 Rtc_GetDateAsync(undefined4 param_1, undefined4 param_2, undefined4 param_3);
undefined4 Rtc_GetDate(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                       undefined4 param_4);
undefined4 Rtc_GetTimeAsync(undefined4 param_1, undefined4 param_2, undefined4 param_3);
undefined4 Rtc_GetTime(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                       undefined4 param_4);
undefined4 Rtc_GetDateTimeAsync(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                                undefined4 param_4);
undefined4 Rtc_GetDateTime(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                           undefined4 param_4);
void RtcCommonCallback(undefined4 param_1, unsigned int param_2, int param_3, undefined4 param_4);
int RtcBcd2Hex(unsigned int param_1);
void RtcGetResultCallback(undefined4 param_1);
void RtcWaitBusy(void);
void Rtci_ReadRawDateTimeAsync(void);
void Rtci_ReadRawDateAsync(void);
void Rtci_ReadRawTimeAsync(void);
void Rtci_WriteRawStatus2Async(void);
bool RtcSendPxiCommand(unsigned int param_1, undefined4 param_2, undefined4 param_3,
                       undefined4 param_4);
int Rtc_ConvertDateToDay(unsigned int* param_1);
int Rtci_ConvertTimeToSecond(int* param_1);
int Rtc_ConvertDateTimeToSecond(undefined4 param_1, undefined4 param_2);
int64_t Rtc_GetDayOfWeek(int* param_1);
void Cardi_SetTask(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void Cardi_LockResource(int param_1, int param_2);
void Cardi_UnlockResource(int param_1, int param_2);
void Cardi_InitCommon(void);
undefined4 Card_IsEnabled(void);
void Card_CheckEnabled(void);
void Card_Enable(bool enable);
bool Cardi_WaitAsync(void);
bool Cardi_TryWaitAsync(void);
undefined4 Card_IsAvailable(void);
void Card_LockRom(undefined4 param_1);
void Card_UnlockRom(undefined4 param_1);
void Card_LockBackup(undefined4 param_1);
void Card_UnlockBackup(undefined4 param_1);
void Cardi_IdentifyBackupCore(unsigned int param_1);
void Cardi_RequestStreamCommandCore(int* param_1);
bool Cardi_RequestStreamCommand(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                                undefined4 param_4, undefined4 param_5, int param_6,
                                undefined4 param_7, undefined4 param_8, undefined4 param_9);
undefined4 Card_GetCurrentBackupType(void);
undefined4 Card_GetBackupTotalSize(void);
undefined4 Card_GetBackupSectorSize(void);
undefined4 Card_GetBackupPageSize(void);
bool Card_IdentifyBackup(int param_1);
void Card_WaitBackupAsync(void);
void Card_TryWaitBackupAsync(void);
bool Cardi_ReadFromCache(void* p);
void Cardi_SetRomOp(uint32_t cmd1, uint32_t cmd2);
void Cardi_SetCardDma(void);
void Cardi_OnReadCard(void);
bool Cardi_TryReadCardDma(int param_1);
void Cardi_ReadCard(void* p);
undefined4 Cardi_ReadRomIdCore(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                               undefined4 param_4);
void Cardi_ReadRomSyncCore(void);
void Cardi_ReadRom(unsigned int param_1, int param_2, undefined4 param_3, undefined4 param_4,
                   undefined4 param_5, undefined4 param_6, int param_7);
void Card_Init(void);
void Card_WaitRomAsync(void);
undefined* Cardi_GetRomAccessor(void);
void Cardi_OnFifoRecv(enum pxi_fifo_tag tag, uint32_t data, bool err);
void Cardi_TaskThread(void);
bool Cardi_Request(undefined4* param_1, int param_2, int param_3);
void Card_InitPulledOutCallback(void);
void Cardi_PulledOutCallback(undefined4 param_1, unsigned int param_2);
undefined4 Card_IsPulledOut(void);
void Card_TerminateForPulledOut(void);
void Cardi_CheckPulledOutCore(int param_1);
void Cardi_SendtoPxi(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                     undefined4 param_4);
void WM_Init(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
undefined4 WmInitCore(int* param_1, unsigned int param_2, undefined4 param_3);
int WM_Finish(void);
void WMi_SetCallbackTable(int param_1, undefined4 param_2);
uint16_t* WmGetCommandBuffer4Arm7(void);
undefined4 WMi_SendCommand(undefined2 param_1, unsigned int param_2, undefined4 param_3,
                           undefined4 param_4);
undefined4 WMi_SendCommandDirect(undefined4* param_1, unsigned int param_2);
undefined4 WMi_GetSystemWork(void);
undefined4 WMi_CheckInitialized(void);
int WMi_CheckIdle(void);
int WMi_CheckStateEx(unsigned int param_1, undefined4 param_2, undefined4 param_3,
                     undefined4 param_4);
void WmReceiveFifo(undefined4 param_1, uint16_t* param_2, int param_3);
void WmClearFifoRecvFlag(void);
undefined4 WMi_GetStatusAddress(void);
undefined2 WM_GetAid(void);
unsigned int WM_GetConnectedAids(void);
undefined2 WMi_GetMpReadyAids(void);
int WM_SetIndCallback(undefined4 param_1);
int WM_SetPortCallback(int param_1, void** param_2, undefined4 param_3, undefined4 param_4);
int WM_ReadStatus(int param_1);
unsigned int WM_GetMpSendBufferSize(void);
int WM_GetMpReceiveBufferSize(void);
int WM_ReadMpData(int param_1, unsigned int param_2, undefined4 param_3, undefined4 param_4);
undefined2 WM_GetAllowedChannel(void);
undefined2 WM_GetLinkLevel(void);
unsigned int WM_GetDispersionBeaconPeriod(void);
unsigned int WM_GetDispersionScanPeriod(void);
void WM_GetOtherElements(undefined4* param_1, uint16_t* param_2, undefined4 param_3,
                         undefined4 param_4);
unsigned int WM_GetNextTgid(void);
int WMi_EnableEx(undefined4 param_1);
int WM_Disable(undefined4 param_1);
int WM_PowerOn(undefined4 param_1);
int WM_PowerOff(undefined4 param_1);
int WMi_InitializeEx(undefined4 param_1, undefined4 param_2, undefined4 param_3);
int WM_Reset(undefined4 param_1);
int WM_End(undefined4 param_1);
int WM_SetParentParameter(undefined4 param_1, int* param_2, undefined4 param_3, undefined4 param_4);
undefined4 WmCheckParentParameter(int param_1);
int WMi_StartParentEx(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                      undefined4 param_4);
void WM_StartParent(undefined4 param_1);
int WM_EndParent(undefined4 param_1);
int WM_StartScan(undefined4 param_1, int* param_2, undefined4 param_3, undefined4 param_4);
int WM_StartScanEx(undefined4 param_1, int* param_2);
int WM_EndScan(undefined4 param_1);
int WM_StartConnectEx(undefined4 param_1, uint16_t* param_2, undefined4* param_3,
                      undefined4 param_4, undefined2 param_5);
int WM_Disconnect(undefined4 param_1, unsigned int param_2);
int WM_DisconnectChildren(undefined4 param_1, unsigned int param_2);
int WMi_StartMp(undefined4 param_1, undefined4 param_2, unsigned int param_3, undefined4 param_4,
                uint16_t param_5, undefined4 param_6);
void WM_StartMpEx(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4,
                  undefined2 param_5, int param_6, undefined2 param_7, undefined1 param_8,
                  undefined1 param_9, int param_10, undefined1 param_11);
void WM_StartMp(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4,
                undefined2 param_5, undefined2 param_6);
int WM_SetMpDataToPortEx(undefined4 param_1, undefined4 param_2, int param_3, unsigned int param_4);
int WM_EndMp(undefined4 param_1);
int WM_StartDcf(undefined4 param_1, int param_2, unsigned int param_3);
int WM_SetDcfData(undefined4 param_1, undefined4* param_2, undefined4 param_3,
                  unsigned int param_4);
int WM_EndDcf(undefined4 param_1);
int WM_StartDataSharing(undefined4* param_1, unsigned int param_2, int param_3, int16_t param_4,
                        int param_5);
undefined4 WM_EndDataSharing(int param_1);
int WM_StepDataSharing(int param_1, int param_2, int param_3);
void WmDataSharingSetDataCallback(int param_1);
void WmDataSharingReceiveCallback_Parent(int param_1);
void WmDataSharingReceiveCallback_Child(int param_1);
void WmDataSharingReceiveData(int param_1, unsigned int param_2, int param_3, undefined4 param_4);
void WmDataSharingSendDataSet(int param_1, int param_2, undefined4 param_3, undefined4 param_4);
void WM_GetSharedDataAddress(int param_1, uint16_t* param_2, unsigned int param_3,
                             undefined4 param_4);
int WmGetSharedDataAddress(int param_1, unsigned int param_2, int param_3, unsigned int param_4);
void WM_StartKeySharing(undefined4 param_1, undefined4 param_2);
void WM_EndKeySharing(void);
int WM_SetWepKey(undefined4 param_1, unsigned int param_2, int param_3);
int WM_SetWepKeyEx(undefined4 param_1, unsigned int param_2, undefined4 param_3, int param_4);
int WM_SetGameInfo(undefined4 param_1, int param_2, unsigned int param_3);
int WM_SetBeaconIndication(undefined4 param_1, unsigned int param_2);
int WM_SetLifeTime(undefined4 param_1, undefined4 param_2, undefined4 param_3);
int WM_MeasureChannel(undefined4 param_1, undefined2 param_2, undefined2 param_3,
                      undefined2 param_4, undefined2 param_5);
void MB_CommSetParentStateCallback(undefined4 param_1);
int MB_CommGetChildUser(int param_1);
undefined4 MB_CommIsBootable(int param_1);
undefined4 MB_CommResponseRequest(int param_1, undefined4 param_2);
void MBi_CommChangeParentState(int param_1, undefined4 param_2, undefined4 param_3);
void MBi_CommChangeParentStateCallbackOnly(void);
void MBi_CommParentCallback(int param_1, undefined2* param_2, undefined4 param_3,
                            unsigned int param_4);
void MBi_CommParentRecvDataPerChild(int param_1, unsigned int param_2, undefined4 param_3,
                                    undefined4 param_4);
void MBi_CommParentRecvData(undefined4 param_1);
void MBi_CommParentSendMsg(undefined1 param_1, undefined4 param_2);
undefined4 MBi_CommParentSendDlfileInfo(void);
void MBi_ReloadCache(int param_1);
undefined4 MBi_CommParentSendBlock(void);
void MBi_CommParentSendData(void);
void MBi_Calc_Sendblock(unsigned int param_1);
unsigned int MBi_Calc_Nextsendblock(unsigned int param_1, unsigned int param_2);
undefined4 IsChildAidValid(unsigned int param_1);
void MBi_CommCallParentError(undefined4 param_1, undefined2 param_2, undefined4 param_3,
                             undefined4 param_4);
unsigned int MB_GetSegmentLength(int param_1, undefined4 param_2, undefined4 param_3,
                                 undefined4 param_4);
int MB_ReadSegment(undefined1* param_1, undefined4* param_2, unsigned int param_3,
                   undefined4 param_4);
void ret_0207484c(void);
void MBi_ReadSegmentHeader(unsigned int* param_1, unsigned int param_2, unsigned int param_3,
                           int param_4);
undefined4 MB_RegisterFile(int param_1, int param_2, undefined4 param_3, undefined4 param_4);
void MBi_MakeDownloadFileInfo(undefined4* param_1, int param_2);
void MBi_SetSegmentInfo(int param_1, int* param_2, int* param_3, int* param_4);
undefined4 MBi_MakeBlockInfoTable(int param_1, int param_2);
undefined4 MBi_Get_Blockinfo(int* param_1, int param_2, unsigned int param_3, int param_4);
undefined4 MBi_IsAbleToRecv(int param_1, unsigned int param_2, int param_3);
unsigned int IsAbleToLoad(int param_1, unsigned int param_2, unsigned int param_3);
void MBi_BlockHeaderEnd(int param_1, undefined4 param_2, undefined4 param_3);
unsigned int MBi_Calc_Cksum(uint16_t* param_1, int param_2);
void MBi_MakeGameInfo(int16_t* param_1, int param_2, int param_3);
undefined4 MBi_ReadIconInfo(int param_1, int param_2, int param_3);
void MB_UpdateGameInfoMember(int param_1, int param_2, unsigned int param_3, undefined2 param_4);
int mystrlen(int16_t* param_1);
void MB_AddGameInfo(int param_1);
void MB_InitSendGameInfoStatus(void);
void MBi_ClearSendStatus(void);
void MB_SendGameInfoBeacon(undefined4 param_1, undefined4 param_2, undefined4 param_3);
undefined4 MBi_ReadyBeaconSendStatus(void);
void MBi_InitSendFixedBeacon(void);
void MBi_SendFixedBeacon(undefined4 param_1, undefined4 param_2, int8_t param_3,
                         undefined4 param_4);
void MBi_InitSendVolatBeacon(void);
void MBi_SendVolatBeacon(undefined4 param_1, undefined4 param_2, int8_t param_3);
undefined4 ChangeScanChannel(int param_1);
bool MBi_IsSendEnabled(void);
void MBi_OnInitializeDone(void);
void MBi_EndCommon(undefined4 param_1);
void MBi_ParentCallback(uint16_t* param_1);
void MBi_ChildPortCallback(int param_1);
void MBi_ChildCallback(uint16_t* param_1);
int64_t MBi_GetBeaconPeriodDispersion(void);
undefined4 MB_Init(int param_1, undefined4* param_2, undefined4 param_3, int param_4,
                   undefined2 param_5);
bool MBi_IsCommSizeValid(unsigned int param_1, unsigned int param_2, int param_3);
undefined4 MB_SetParentCommParam(undefined4 param_1, undefined4 param_2);
undefined4 MBi_StartCommon(void);
undefined4 MBi_StartParentCore(undefined2 param_1);
void MB_StartParent(void);
int MBi_CallReset(void);
undefined4 MBi_CommEnd(void);
void MB_End(void);
void MB_DisconnectChild(unsigned int param_1, undefined4 param_2, undefined4 param_3,
                        undefined4 param_4);
void MBi_GetLastFountParent(undefined2 param_1);
undefined4 MBi_GetParentBssDesc(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                                undefined4 param_4, undefined2 param_5);
int MBi_SendMp(unsigned int param_1, undefined2 param_2, undefined2 param_3);
undefined4 MBi_GetGgid(void);
undefined2 MBi_GetTgid(void);
unsigned int MBi_GetAttribute(void);
bool MBi_IsStarted(void);
void MBi_CheckWmErrcode(undefined2 param_1, int param_2);
void MBi_InitCache(undefined4 param_1);
void MBi_AttachCacheBuffer(int param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4,
                           undefined4 param_5);
undefined4 MBi_ReadFromCache(undefined4* param_1, int param_2, undefined4* param_3,
                             unsigned int param_4);
void MBi_InitTaskThread(struct thread* param_1, int param_2);
bool MBi_IsTaskAvailable(void);
void MBi_InitTaskInfo(undefined4 param_1);
bool MBi_IsTaskBusy(int param_1);
void MBi_SetTask(undefined4* param_1, undefined4 param_2, undefined4 param_3, unsigned int param_4);
void MBi_EndTaskThread(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                       undefined4 param_4);
void MBi_SetChildMpMaxSize(int param_1);
void MBi_SetParentPieceBuffer(undefined4 param_1);
void MBi_ClearParentPieceBuffer(int param_1);
undefined1* MBi_MakeParentSendBuffer(undefined1* param_1, undefined1* param_2);
char* MBi_SetRecvBufferFromChild(char* param_1, char* param_2, int param_3);
int MBi_ReceiveRequestDataPiece(int param_1, int param_2);
undefined4 IsGetAllRequestData(int param_1);
void Ctrdgi_InitCommon(void);
undefined4 Ctrdgi_IsBitIdAtInit(void);
undefined4 Ctrdg_IsOptionCartridge(void);
int8_t Ctrdgi_GetModuleInfoAddr(void);
undefined4 Ctrdg_IsNumberID(void);
undefined4 Ctrdg_IsAgbCartridge(void);
undefined4 Ctrdg_IsAgbCartridgePulledOut(void);
undefined2 Ctrdgi_IsAgbCartridgeAtInit(void);
undefined4 Ctrdg_IsExisting(void);
void Ctrdgi_ChangeLatestAccessCycle(void* r);
void Ctrdgi_RestoreAccessCycle(void* r);
void Ctrdgi_LockByProcessor(uint16_t lock_id, void* info);
void Ctrdgi_UnlockByProcessor(uint16_t lock_id, void* info);
void Ctrdgi_SendtoPxi(uint32_t data);
bool Ctrdg_Read8(undefined4 param_1, undefined4 param_2);
bool Ctrdgi_AccessCommon(undefined4* param_1, undefined4 param_2, undefined4* param_3,
                         unsigned int param_4);
undefined4 Ctrdg_IsEnabled(void);
void Ctrdg_Enable(int param_1);
void Ctrdg_CheckEnabled(void);
void Ctrdg_Init(void);
// If declaring these builtins causes issues, you can disable them
#ifndef PRSOA_NO_BUILTIN
void Ctrdgi_InitModuleInfo(void);
void Ctrdgi_CallbackForInitModuleInfo(undefined4 param_1, unsigned int param_2);
void Ctrdgi_PulledOutCallback(undefined4 param_1, unsigned int param_2);
void Ctrdg_TerminateForPulledOut(void);
void Ctrdgi_CallbackForSetPhi(void);
void Ctrdgi_InitTaskThread(struct thread* param_1);
void Ctrdgi_InitTaskInfo(undefined4 param_1);
void Ctrdgi_IsTaskBusy(int param_1);
unsigned int Math_CountPopulation(unsigned int param_1);
void Mathi_Crc16InitTableRev(uint16_t* param_1, unsigned int param_2);
void Mathi_Crc16UpdateRev(int param_1, uint16_t* param_2, int8_t* param_3, unsigned int param_4);
unsigned int Math_CalcCrc16(undefined4 param_1, undefined4 param_2, undefined4 param_3,
                            unsigned int param_4);
char* Std_CopyString(char* param_1, char* param_2);
void Std_CopyLStringZeroFill(int param_1, char* param_2, int param_3);
int Std_GetStringLength(char* param_1);
int Std_ConcatenateString(int param_1, char* param_2);
int Std_CompareString(char* param_1, char* param_2);
int Std_CompareNString(int param_1, int param_2, int param_3);
void string_put_char(int* param_1, undefined1 param_2);
void string_fill_char(unsigned int* param_1, undefined1 param_2, unsigned int param_3);
void string_put_string(unsigned int* param_1, int param_2, unsigned int param_3);
int OS_VsNPrintfEx(undefined1* param_1, int param_2, int8_t* param_3, unsigned int* param_4);
int32_t abs(int32_t x);
void ret_020794d4(void);
int32_t mbtowc(wchar_t* pwc, const char* s, size_t n);
bool TryAssignByte(uint8_t* ptr, uint8_t val);
bool TryAssignByteWrapper(uint8_t* ptr, uint8_t val);
size_t wcstombs(char* dest, const wchar_t* src, size_t n);
void* memcpy(void* dest, const void* src, size_t n);
void* memmove(void* dest, const void* src, size_t n);
int __vsprintf_internal_slice(slice_append_fn_t append, struct slice* str, const char* format,
                              va_list ap);
bool TryAppendToSlice(struct slice* slice, const void* data, size_t data_len);
int __vsprintf_internal(char* str, size_t maxlen, const char* format, va_list ap);
int vsprintf(char* str, const char* format, va_list ap);
size_t strlen(const char* s);
char* strcpy(char* dest, const char* src);
char* strncpy(char* dest, const char* src, size_t n);
char* strcat(char* dest, const char* src);
int32_t strcmp(const char* s1, const char* s2);
int32_t strncmp(const char* s1, const char* s2, size_t n);
char* strchr(const char* string, int32_t c);
char* strstr(const char* haystack, const char* needle);
void ret_0207f910(void);
void ret_0207f9c0(void);
double _dadd(double a, double b);
unsigned long long _ll_ufrom_d(double d);
double _dmul(double a, double b);
double _drsub(double b, double a);
double _dsub(double a, double b);
float _fadd(float a, float b);
bool _dls(double a, double b);
bool _deq(double a, double b);
bool _fls(float a, float b);
float _frdiv(float divisor, float dividend);
float _fdiv(float dividend, float divisor);
int32_t _ffix(float f);
float _fflt(int32_t i);
float _fmul(float a, float b);
float _fsub(float a, float b);
long long _ll_mod(long long dividend, long long divisor);
long long _ll_sdiv(long long dividend, long long divisor);
unsigned long long _ll_udiv(unsigned long long dividend, unsigned long long divisor);
unsigned long long _ull_mod(unsigned long long dividend, unsigned long long divisor);
long long _ll_mul(long long a, long long b);
unsigned long long _s32_div_f(int dividend, int divisor);
void _u32_div_f(uint32_t param_1, uint32_t param_2);
void _u32_div_not_0_f(uint32_t param_1, uint32_t param_2);
void ret_02081c00(void);
void ret_02082e20(void);
void ret_02083544(void);
#endif

#endif
